mach3-software/MaCh3

Diagnostics/RHat.cpp
manager/manager.cpp
samplePDF/Structs.h
samplePDF/samplePDFBase.cpp
samplePDF/samplePDFBase.h
splines/gpuSplineUtils.cu

Changes texture object into texture refercne (same as in recent cahnges on T2K) to enable CUDA 11 support.
Minor tweak to LLH calc after discussion with Lukas Berns

CUDA 11 suport for the core code/New LLH/R hat estimator

---

CMakeLists.txt
Diagnostics/Diagnostics_utils/PlotMCMC_Diagnosis.cpp
Diagnostics/RHat.cpp
covariance/covarianceBase.h
covariance/covarianceXsec.cpp
covariance/covarianceXsec.h
mcmc/CMakeLists.txt
mcmc/MCMCProcessor.cpp
mcmc/MCMCProcessor.h
mcmc/gpuMCMCProcessorUtils.cu
samplePDF/Structs.cpp
samplePDF/Structs.h
samplePDF/samplePDFBase.cpp
samplePDF/samplePDFBase.h
splines/CMakeLists.txt
splines/SplineMonolith.cpp
splines/SplineMonolith.h
splines/gpuSplineUtils.cu

Basically move all my recent work from T2K branch here

Random Features from T2K

---

CMakeLists.txt
Diagnostics/Diagnostics_utils/PlotMCMC_Diagnosis.cpp
Diagnostics/RHat.cpp
covariance/covarianceBase.h
covariance/covarianceXsec.cpp
covariance/covarianceXsec.h
mcmc/CMakeLists.txt
mcmc/FitterBase.cpp
mcmc/FitterBase.h
mcmc/LikelihoodFit.cpp
mcmc/LikelihoodFit.h
mcmc/MCMCProcessor.cpp
mcmc/MCMCProcessor.h
mcmc/MinuitFit.cpp
mcmc/MinuitFit.h
mcmc/gpuMCMCProcessorUtils.cu
mcmc/mcmc.cpp
mcmc/mcmc.h
samplePDF/Structs.cpp
samplePDF/Structs.h
samplePDF/samplePDFBase.cpp
samplePDF/samplePDFBase.h
splines/CMakeLists.txt
splines/SplineMonolith.cpp
splines/SplineMonolith.h
splines/gpuSplineUtils.cu

Implement Minuit interface.
```
FitterBase->mcmc
->LikelihoodFit->MinuitFit
```
All valdiations were done using T2K branch and presented at T2K meetings.

Feature Minuit [core]

---

CMakeLists.txt
Diagnostics/RHat.cpp
mcmc/MCMCProcessor.cpp
mcmc/MCMCProcessor.h
splines/SplineMonolith.cpp
splines/gpuSplineUtils.cu

Yet another MCMC processor update

---

mcmc/CMakeLists.txt

There was a small typo in CMakeLists that stopped it compiling
Changes gpuMCMC->gpuMCMCProcessorUtils

Noticed tiny issue in the GPU only build that stops it compiling

---

CMakeLists.txt

Adding `-DUSE_CPU` will disable GPU [maybe change this to GPU_OFF to make it clearer]

Lets user manually disable GPU

---

covariance/covarianceBase.cpp
mcmc/FitterBase.h
mcmc/LikelihoodFit.h
mcmc/MCMCProcessor.cpp
mcmc/MCMCProcessor.h
mcmc/MinuitFit.h
mcmc/mcmc.h
samplePDF/Structs.cpp
samplePDF/samplePDFBase.cpp
splines/SplineMonolith.cpp
splines/SplineMonolith.h
splines/gpuSplineUtils.cu

Bunch of updates from T2K only.

MCMC processor Update (again...)

---

Diagnostics/Diagnostics_utils/PlotMCMC_Diagnosis.cpp
covariance/covarianceBase.cpp
covariance/covarianceBase.h
covariance/covarianceXsec.cpp
covariance/covarianceXsec.h
manager/manager.cpp
mcmc/FitterBase.cpp
mcmc/MCMCProcessor.cpp
mcmc/MCMCProcessor.h

Reading in and setting up covarianceXsec from many YAML files.
Then a bit of tidying up in the MCMCProcessor which seems to be working for now.

Feature many yamls

---

Diagnostics/CombineMaCh3Chains.cpp
Diagnostics/DiagMCMC.cpp
Diagnostics/GetPenaltyTerm.cpp
Diagnostics/ProcessMCMC.cpp
Diagnostics/RHat.cpp
manager/MaCh3Logger.h

Main change is inclusion of logger to Rhat, also printout for every toy has changed. So to understand:
before
after
As a bonus allow to redirect cout in external software to MaCh3 logger:

Fancy RHat

---

cmake/Modules/MaCh3Dependencies.cmake
mcmc/CMakeLists.txt
mcmc/MaCh3Factory.cpp
mcmc/MaCh3Factory.h

Factory to allow easy (via conifg) initialsiation of different fitting algorithms

MaCh3 Fitter Factory

---

.gitignore
cmake/Modules/CUDASamples.cmake
cmake/Modules/CUDASetup.cmake

- Only setup cuda samples if needed
- Allow to compile mach to install not build

Cmake cuda fixes

---

.github/ISSUE_TEMPLATE/feature_request.md
covariance/CMakeLists.txt
covariance/PCAHandler.cpp
covariance/PCAHandler.h
covariance/covarianceBase.cpp
covariance/covarianceBase.h
mcmc/FitterBase.cpp
mcmc/FitterBase.h
splines/SplineMonolith.cpp
splines/SplineStructs.h

Implement PCA handler, really it is just moving stuff from CovBase to this new class. Aim is to make CovBase smaller and easier to read. But also PCA within MaCh3 should really be imrpvoed. This allow to make future improvments easier.

PCA Handler

---

splines/SplineMonolith.cpp

See fore more: https://github.com/t2k-software/MaCh3/pull/718

Safer Finding Spline Segment

---

.mailmap
Diagnostics/DiagMCMC.cpp
Diagnostics/GetPostfitParamPlots.cpp
Diagnostics/ProcessMCMC.cpp
mcmc/FitterBase.cpp
mcmc/MCMCProcessor.cpp
mcmc/MCMCProcessor.h

ROOT changed default behaviour of violin plots in R6. Introudce neccessary changes to make violin pltos fancy in R6.
In addition more logger and fixing typos.
Before
After

Violin plot in R6

---

manager/MaCh3Modes.cpp
mcmc/mcmc.cpp

Couple of tiny fixes I came across while trying to debug something else
two variables misnames which was stopping code from compiling in debug mode
NA

Fix debug build

---

.github/workflows/CIValidations.yml
covariance/covarianceBase.cpp
mcmc/FitterBase.cpp
mcmc/MinuitFit.cpp

This is inpired by issue made by Ewan: https://github.com/mach3-software/MaCh3/issues/95
I made recently new repo holding MaCh3 valdiatations: https://github.com/mach3-software/MaCh3Validations
Currently only Spline testing exist. It is very easy to extend current workflow to Covariance for example.
- Add new CI workflow

CI Validations

---

.github/labeler.yml
.github/workflows/greetings.yml
.github/workflows/label.yml
.mailmap
covariance/covarianceXsec.cpp
covariance/covarianceXsec.h
samplePDF/Structs.h
splines/splineFDBase.cpp

Increase use case of  `SystType` this should make adding more syst types in future even easier.

More Scalable Cov Xsec

---

.github/labeler.yml
CMakeLists.txt
Doc/Doxyfile
Doc/MaCh3.css
Doc/bibliography.bib
Doc/mainpage.md
cmake/Templates/Doxyfile.in
manager/gpuUtils.cuh
mcmc/MCMCProcessor.cpp
mcmc/MCMCProcessor.h
mcmc/MinuitFit.h
mcmc/SampleSummary.h
mcmc/StatisticalUtils.h
samplePDF/Structs.h
samplePDF/samplePDFFDBase.h
splines/splineFDBase.cpp
splines/splineFDBase.h

Doxygen allow to use .bib style bibliography, let's use it to make docuemtnation better and hopefully referencing same paper in several places easier to find.
Also based on testing select best set of optimisation flags
Tidy splineFD and samplePDF headers
Bump version number.
[StepTimeComparison_unroll.pdf](https://github.com/user-attachments/files/16927619/StepTimeComparison_unroll.pdf)
[StepTimeComparison_lto.pdf](https://github.com/user-attachments/files/16927620/StepTimeComparison_lto.pdf)
[StepTimeComparison_inline.pdf](https://github.com/user-attachments/files/16927621/StepTimeComparison_inline.pdf)
[StepTimeComparison_maxTrack.pdf](https://github.com/user-attachments/files/16927622/StepTimeComparison_maxTrack.pdf)

Doxygen bibliography

---

splines/SplineMonolith.cpp
splines/gpuSplineUtils.cu

Minor syntax error fixes & removed some print statements

---

splines/SplineStructs.h

Added GetNp to TF1 struct similar to that in TSpline3, as it's used in T2K MaCh3 (https://github.com/t2k-software/MaCh3/blob/develop/samplePDF/samplePDFND280.cpp#L961)

Added GetNp to TF1 in SplineStructs

---

.github/dependabot.yml
.github/workflows/CIValidations.yml
.github/workflows/TagTutorial.yml
CMakeLists.txt
Doc/Doxyfile
covariance/covarianceOsc.cpp

I renamed Valdaition to Tutorial but Validations still are there, this reauqiers updating CI
Also annoingly current and proposed vladue haven't been set as prior in Cov Osc which could hinder step acceptance...

Changes to CI after I change valaitions into tutorial

---

CMakeLists.txt
Doc/Doxyfile
cmake/Modules/mach3-config.cmake
cmake/Templates/MaCh3Config.cmake.in
covariance/covarianceBase.cpp
covariance/covarianceBase.h
covariance/covarianceXsec.cpp
covariance/covarianceXsec.h
manager/MaCh3Modes.cpp
mcmc/SampleSummary.cpp
plotting/plottingUtils/plottingManager.cpp
splines/SplineCommon.h
splines/SplineMonolith.cpp
splines/SplineStructs.h

Previosly we had this hardcoding isFlux etc. Which was quite bad... For some time in T2K we store ND syst params in Cov Xsec, this make seprate operations on ND Syst quite annoing. With new approach it should be much easier to Fix only ND Syst etc.
- Introduce parmater group
- Remove isFlux etc

Parameter Group

---

splines/CMakeLists.txt
splines/MaCh3SplinesLinkDef.h
splines/SplineMonolith.cpp
splines/SplineMonolith.h
splines/gpuSplineUtils.cuh

Neccessary for this: https://github.com/mach3-software/MaCh3Tutorial/pull/11

Easier Flat Spline Monolith

---

cmake/Modules/MaCh3Dependencies.cmake
covariance/AdaptiveMCMCHandler.cpp
covariance/AdaptiveMCMCHandler.h
covariance/PCAHandler.cpp
covariance/PCAHandler.h
covariance/covarianceBase.cpp
covariance/covarianceBase.h

Move more stuff to Adaptive and PCA handlers. Still there are some questionable choices which I don't like. But at least trying to abstract this a bit.

Tidy Cov handlers

---

.github/workflows/CIValidations.yml
.github/workflows/Stale.yml

See this https://github.com/mach3-software/MaCh3Tutorial/pull/13
Meant to make sure we can convert MaCh3 chain to NuMCMC format becasue why not...

Nu MCMC CI

---

.github/workflows/CIValidations.yml
covariance/covarianceXsec.cpp
covariance/covarianceXsec.h

We have many get blarb deti id. Implement fancy template which redces copy pasting. Main advatange is that det id will probably change in the future if we want support other not hardcdoed experiments.
Also Print() was huge so I divided into several smaller fucntions for each syst type.

Tidy CovXsec

---

.github/workflows/CIValidations.yml
Diagnostics/CombineMaCh3Chains.cpp

More scalable CI Valdiation and dump remaining exectuables. Let's test everything...

More MCMC Diag to CI

---

.github/CODEOWNERS

Testing codoweners

---

.github/CODEOWNERS
.github/workflows/Newsletter.yml

See https://github.com/orgs/mach3-software/discussions/150

Newsletter from bot 

---

mcmc/MCMCProcessor.cpp

Does what it says on the tin really

save the 1d posteriors in MCMCProcessor

---

.github/workflows/Meme.yml

Meme bot test

---

.github/workflows/Doxygen.yml

New docs seem to work nicely so let's actually upload them

Upload docs to pages

---

Doc/mainpage.md

Turns out Mach3 vs MaCh3 still gets me sometimes even after all these years

Fix link in mainpage.md

---

.github/workflows/CIValidations.yml

See https://github.com/mach3-software/MaCh3Tutorial/pull/31

CI Folder Fix

---

mcmc/FitterBase.cpp
mcmc/FitterBase.h
mcmc/mcmc.cpp
mcmc/mcmc.h

Now Start From previous is in Fitter Base this mean every algorith can use it. Hovwerv it is virtual thus every algorithm can load some specyfic inofrmation.
Cheers Dan for comment

More Flexible Start FromPrevious

---

.github/workflows/CIValidations.yml

Simply start proeprly testing sample PDF FD
See https://github.com/mach3-software/MaCh3Tutorial/pull/32

enforece use of new sample CI

---

Doc/Doxyfile
README.md
cmake/Templates/Doxyfile.in
covariance/covarianceBase.cpp
covariance/covarianceBase.h
mcmc/MCMCProcessor.cpp
mcmc/MaCh3Factory.h
mcmc/StatisticalUtils.h
python/samplePDF.cpp
samplePDF/Structs.cpp
samplePDF/samplePDFBase.cpp
samplePDF/samplePDFBase.h
splines/CMakeLists.txt
splines/SplineMonolith.cpp
splines/SplineMonolith.h

Implement SamplePDF Factory, best part is that it uses template so MaCh3 doesn't have to know about type of class. I tested and it works with Tutorial SasmplePDF
https://github.com/mach3-software/MaCh3Tutorial/pull/37

Sample PDF Factory

---

.github/workflows/Newsletter.yml
Diagnostics/ProcessMCMC.cpp
Doc/bibliography.bib
mcmc/MCMCProcessor.h
mcmc/StatisticalUtils.h

Implement MCMC thinning
Update newsleetter not a clue why...

MCMC Thinning

---

.github/workflows/CDImage.yml
Doc/MaCh3DockerFiles/Alma9/Dockerfile
Doc/MaCh3DockerFiles/Fedora32/Dockerfile
Doc/MaCh3DockerFiles/Rocky9/Dockerfile
Doc/MaCh3DockerFiles/Ubuntu22.04/Dockerfile

Henry suggested to incldue it so here it is

pip install to CI/CD

---

.github/workflows/CIPythonValidations.yml

add new workflow which runs the python CI added to the tutorial (in [this PR](https://github.com/mach3-software/MaCh3Tutorial/pull/41#issue-2660614332) which should be merged there first)

Add Python CI

---

mcmc/MaCh3Factory.cpp
mcmc/MaCh3Factory.h

Passing cov and sample pdf to Fitter Facotry is causing more problems than it is helpfull :( It didn't work correctly
Template has to be in header file to work...

Tidy Factory

---

plotting/GetPostfitParamPlots.cpp

TL:DR Tpad are unpredictable I hate them, they like segfaulting. I fixed it.
There are still plenty of memeory leaks but don't have time to do this correctly my priroity was to fix segfault

Fix segfault

---

plotting/PlotLLH.cpp

Bascially what tittle says
[LLHScan_Total.pdf](https://github.com/user-attachments/files/18081833/LLHScan_Total.pdf)

Fix Tittle in LLH plot

---

Diagnostics/CombineMaCh3Chains.cpp

Seeing what lines are different is quite helfpull

feat: Print which settigns are different when merging chians

---

.github/workflows/CIValidations.yml

For more see: https://github.com/mach3-software/MaCh3Tutorial/pull/65

feat: Add  hist CI

---

splines/splineFDBase.cpp

Remove all couts in spline code

tidy: More logger to binned splines

---

.github/CIscripts/RAM.sh
.github/workflows/Telemetry.yml
splines/CMakeLists.txt

This will need some love in future but this bot will make RAM distribution

feat: Telemetry

---

cmake/Modules/NuOscillatorSetup.cmake

Bump NuOscillator to v1.1.0
Includes fixes in OscProb for additional functionality

Feat: Bump NuOscillator to v1.1.0

---

CMakeLists.txt
Doc/Doxyfile
README.md
mcmc/CMakeLists.txt
mcmc/SampleSummary.cpp
mcmc/SampleSummary.h
mcmc/StatisticalUtils.cpp
mcmc/StatisticalUtils.h
samplePDF/HistogramUtils.cpp
samplePDF/HistogramUtils.h

- Now statistical utils is actual library whcih, this means compiler can find problems on compiler level
- There have been plenty of histogram fucntions in SampleSummary, which have been moved to Histogramutils. Hopine we can reuse them in more places
- Minor tidy to readme
- More vectors instead of raw pointers

tidy: Make Statistical utils actual library

---

.github/workflows/CIValidations.yml

This need to be merged first: https://github.com/mach3-software/MaCh3Tutorial/pull/74

feat: Statistial utist test

---

.github/workflows/CIPythonValidations.yml

breaking: Temporary turn off python CI

---

samplePDF/samplePDFBase.h
samplePDF/samplePDFFDBase.cpp

There is plenty of repetition in how we select norm bins. Made simple template whcih allow to simplyfi and reduce hardcoding

tidy: Smarter getting Norm bin

---

mcmc/SampleSummary.cpp
mcmc/SampleSummary.h
mcmc/StatisticalUtils.cpp
mcmc/StatisticalUtils.h

2D pValue calcuation are generic enough that could be used outside of SampleSummary class. My hope we can use it in other fucntionality (not specified at the moment)

tidy: Generalise 2D pvalue code

---

samplePDF/samplePDFFDBase.cpp
samplePDF/samplePDFFDBase.h

There were 3 isEvent slected with lot of copy pasting. We only use one so remvoed other. If for some reason we still need them, then can bring them back but using some more clever code to reuse them.

tidy: is event selected

---

covariance/CovarianceUtils.h
manager/Monitor.cpp
manager/Monitor.h
manager/manager.cpp
mcmc/FitterBase.cpp

Main idea is to print how many htreads are being used. Yesterday I enouctered somone using 64 threads which had terrible impact on performance. This minor thing is supposed to make finidng such mistakes easier.

tidy: More infor about threads

---

.github/CIscripts/RAM.sh

Increase number of steps for telemtry bot from 10k to 100k. It should allow to more easily spot memory leaks etc.

feat: Longer Running Telemetry Bot

---

mcmc/FitterBase.cpp
mcmc/FitterBase.h
mcmc/mcmc.cpp
mcmc/mcmc.h

PR to include the chain restart fix into main

feat: Chain restart fix

---

mcmc/FitterBase.cpp
mcmc/FitterBase.h

- Stop saving tvector with prior as we have full yaml file
- Remove uneccesary return
- Use safer yaml getters

tidy: safer Fitter Base

---

cmake/Modules/NuOscillatorSetup.cmake

Bump NuOscillator to v1.2.0 and pick up all the associated changes (https://github.com/dbarrow257/NuOscillator/releases/tag/v1.2.0)

feat: Bump NuOscillator to v1.2.0

---

.github/workflows/CIPythonValidations.yml

Needed after this one is merged
https://github.com/mach3-software/MaCh3Tutorial/pull/84

tidy: Update CIPythonValidations.yml

---

covariance/covarianceBase.cpp
splines/SplineMonolith.cpp
splines/gpuSplineUtils.cu

Increase perofmance by not repating same calucation several times.

feat: Crackpot speedup

---

cmake/Modules/NuOscillatorSetup.cmake

Simply it is bit hacky but I am tired of seeing people encountering this problem

bugfix: Stop seeing CUDALinear on GPU problem

---

README.md

Update description of oscialtion engines that MaCh3 has access via NuOscillator

tidy: Update Readme

---

CMakeLists.txt
Doc/Doxyfile
python/splines.cpp
samplePDF/samplePDFFDBase.cpp
splines/SplineBase.cpp
splines/SplineBase.h
splines/SplineMonolith.cpp
splines/SplineMonolith.h
splines/SplineStructs.h
splines/splineFDBase.cpp
splines/splineFDBase.h

Simply move almos identical find spline segment to spline base.
Minor hacks are need related with SplineSegments to support GPU splines for EventByEvent

feat: Unify find spline segment

---

manager/manager.cpp
mcmc/StatisticalUtils.cpp
python/samplePDF.cpp
samplePDF/Structs.h
samplePDF/samplePDFBase.cpp

Stop hardcoding names and make easier to include more test statistics in future
First this must be merged
https://github.com/mach3-software/MaCh3Tutorial/pull/90

tidy: More scalable test statisctic selection

---

README.md
cmake/Modules/NuOscillatorSetup.cmake

Include NuSQUIDSLinear support, USE_NuFastLiner->USE_NuFastLinear

feat: Bump to NuOsc v1.2.1

---

.github/workflows/CIBuild.yml
Doc/MaCh3DockerFiles/Ubuntu24.10/Dockerfile
README.md

feat: Clang bot

---

samplePDF/samplePDFFDBase.cpp

Fixing silly destructor mistake

bugfix: Fix destructor of THStackLeg 

---

manager/MaCh3Modes.cpp
manager/MaCh3Modes.h

feat: Add SplineSuffix to MaCh3Modes object

---

splines/splineFDBase.cpp
splines/splineFDBase.h

feat: Move StripDuplicatedSplines and GetEventSplines to splineFDBase

---

covariance/covarianceBase.cpp
manager/MaCh3Modes.cpp
manager/MaCh3Modes.h

Use default drawing for UNKNOWN_BAD to be kBlack
SplineSuffix was wrongly being printed

tidy: Tweak to MaCh3 mode

---

splines/splineFDBase.cpp
splines/splineFDBase.h

feat: Move FillSampleArray to splineFDBase

---

samplePDF/samplePDFFDBase.cpp
splines/splineFDBase.cpp
splines/splineFDBase.h

AddSample is now void not bool.
Simlfy some of stupid loops in SplineFD.
There is still SO MUCH MESS in this class but don't have more time right now

tidy: Remove parts of terrible loops in SplineFD

---

splines/splineFDBase.cpp

bugfix: Fix check on MaCh3Modes in splineFDBase constructor

---

CMakeLists.txt
Doc/Doxyfile
samplePDF/Structs.h
splines/splineFDBase.cpp
splines/splineFDBase.h

- bump version
- Don't use strcmp instead simple ==
- more doxygen comments
- const correctness
- logger and MaCh3Exception

Tidy: Post SplineFD cleanup tidy

---

manager/MaCh3Modes.cpp
manager/MaCh3Modes.h

feat: Add counter for CC modes in MaCh3Modes object

---

splines/splineFDBase.cpp

feat: Add protection against duplicate splines in splineFDBase

---

splines/splineFDBase.cpp
splines/splineFDBase.h

feat: Quicker duplicate spline checking

---

samplePDF/samplePDFFDBase.cpp

bugfix: Include support for 1D samples in samplePDFFDBase::PrintIntegral

---

.github/workflows/CIValidations.yml

This will work once this is merged
https://github.com/mach3-software/MaCh3Tutorial/pull/100

feat: Add to CI new plotting tool in tutorial

---

samplePDF/HistogramUtils.h
samplePDF/samplePDFBase.cpp
samplePDF/samplePDFBase.h
samplePDF/samplePDFFDBase.cpp
samplePDF/samplePDFFDBase.h
splines/splineFDBase.h

You cannot cast in c++ vector but you can write simple template function which will do the casting.
In addiditon use `Get` from Yaml helpers which has built in check for node exsiting
https://github.com/mach3-software/MaCh3/blob/f68b8e074e1c15a38218b2f076b4275fe2c349a4/manager/YamlHelper.h#L262
this allows to make loading Sample Config easier

feat: Improve Vector Casting

---

.github/workflows/CIValidations.yml
CMakeLists.txt
Doc/Doxyfile
mcmc/FitterBase.cpp

Add sigma var bot and intorudce std::vecotr instead of raw pointer

feat: Sigma Var Bot

---

cmake/Modules/NuOscillatorSetup.cmake
splines/splineFDBase.cpp

feat: Stop the spammy message for additional splines

---

CMakeLists.txt
splines/splineFDBase.cpp

bugfix: Correctly handle duplicate modes in GetEventSplines

---

CMakeLists.txt
Doc/Doxyfile
samplePDF/samplePDFFDBase.cpp

Change loop ordering in get likelihood for better cache hits

feat: LLH Cache hits

---

cmake/Modules/NuOscillatorSetup.cmake

Change NuOscillator verion to have this fancy new feature
https://github.com/dbarrow257/NuOscillator/releases/tag/v1.3.0

feat: Bump NuOscillator

---

.github/workflows/CIBuild.yml
Doc/MaCh3DockerFiles/Rocky9/Dockerfile
Doc/MaCh3DockerFiles/Ubuntu22.04/Dockerfile
cmake/Modules/NuOscillatorSetup.cmake

- By default MaCh3 compile with NuFast for Beam and CudaProb3 for ATM
- More GPU checks like GPU debug GPU float etc
- GPU contianer now make sure GPU has been compiled

feat: More robust GPU CI

---

manager/Monitor.cpp
manager/Monitor.h
mcmc/FitterBase.cpp
mcmc/mcmc.cpp

Do not allow people to use more than 16 threads. With so many code will be slower. Now there are plenty of modern CPU which can have even 64 or more threads.
In addition tidy yaml usage

feat: N Threas Sanity Check

---

.github/CONTRIBUTING.md
CONTRIBUTING.md
README.md

Add information of the versioning scheme that this package will follow
Based on discussion in [#mach3_crossexperiment_dev](https://t2k-experiment.slack.com/archives/C08MMSCFWDV/p1745424067592049)
Information added to new `CONTRIBUTING.md`

tidy: explain versioning of this package in CONTRIBUTING.md

---

CMakeLists.txt
cmake/Modules/NuOscillatorSetup.cmake

Recently issues have been spotted with GPU part of CudaProb3
https://github.com/dbarrow257/NuOscillator/issues/115
This feature allow to turn off GPU for NuOsc while giving ability to still compile MaCh3 with GPU (moslty for GPU SplineMonolith)

feat: Ability to turn off gpu for NuOsc

---

samplePDF/Structs.h
splines/splineFDBase.cpp
splines/splineFDBase.h

- There were no clean vector for 7D thus index wasn't properly delete
- UniqueSystIndices wasn't dleted at all
- TSpline3_red should delte my spline so added protection, we were dleting nullptr, I don't have a clue why code was fine...
- Trying to pass strings and vectors via reference

feat: Minor RAM tweaks for spline

---

.github/workflows/WeeklyValgrind.yml

Idea is to always have up to date valgrind output, they will be udpated weekly here:
https://github.com/mach3-software/MaCh3/tree/gh-profiling
Bot commit https://github.com/mach3-software/MaCh3/commit/34392af70814922b2dc8ed8860248a8178965f7b
Actual run: https://github.com/mach3-software/MaCh3/actions/runs/14650598029/job/41115219300

feat: Valgrind bot

---

.github/pull_request_template.md

Whnever somone tries to make PR it will be notified about contributing, this hopefully will make people more aware about contirbuting

feat: Notify about contributing

---

manager/YamlHelper.h

Make check to avoid situations like this: https://github.com/mach3-software/MaCh3/issues/268
---

feat: Safer Yaml Handling

---

manager/MaCh3Modes.cpp
mcmc/MaCh3Factory.h
mcmc/PSO.cpp
splines/SplineCommon.h

- Try to use Get whcih has proper protection and error handling
- BadSpline wasn\t used anywhere
---

tidy: Minor Yaml and Spline tidy

---

cmake/Modules/NuOscillatorSetup.cmake

feat: Update NuOscillatorSetup.cmake to use v1.3.1

---

samplePDF/samplePDFFDBase.cpp
samplePDF/samplePDFFDBase.h

I was testing SharedNuOsc destructor here: https://github.com/mach3-software/MaCh3Tutorial/pull/117
Long term goal I think we should use shared_pointer for such cases but do this small hack for now to avoid segfault in desctuctor.
---

bugfix: Fix Shared NuOsc destructor

---

.github/workflows/TaskChecker.yml

This bot enforces that people actually marked that they have read contributing guidelines
Test that it works
---

feat: Bot for Task Checking

---

.github/workflows/Newsletter.yml

Simply expand newsletter to also include number of PR for fun...
---

feat: Expand Newsletter

---

.github/workflows/CIBuild.yml
Doc/MaCh3DockerFiles/Ubi9/Dockerfile
README.md

Simply add anohter cotnainer this time using Ubi9.
https://github.com/mach3-software/MaCh3/actions/runs/14954542733/job/42008453947?pr=441
---

feat: Ubi9 Cuda Container

---

Parameters/PCAHandler.cpp
Parameters/PCAHandler.h
Parameters/ParameterHandlerGeneric.cpp
Parameters/ParameterHandlerOsc.cpp

Now we have PCA prefitit intlasiton in PCA handler.
---

tidy: PCA prefit intialsition now in PCA Hnadler

---

README.md

Info how to change logger was missing from readme so let's add it
---

tidy: Logger to readme

---

.github/workflows/CodeQL.yml

Previously we were testing with CodeQL CPU implementation. It might be wroth to also test GPU. Why not more bots
---

feat: Expand CodeQL to also perform GPU compilation

---

Parameters/ParameterHandlerBase.cpp
Parameters/ParameterHandlerBase.h

Having adaptive MCMC as pointer means several things
- No longer allocate memory if we don't use adaptive
- Potetnially faster code due to caches
- Most importantly, in future we might want to have proper adaption factory, different algorigh etc. Then pointer make it nicer.
---

tidy: Adaptive Handler into pointer

---

.github/workflows/CodeQL.yml

Here I udpated code QL but was too lazy to check it:
https://github.com/mach3-software/MaCh3/pull/454
This time I actually checked:
https://github.com/mach3-software/MaCh3/actions/runs/15108421261/job/42462121223
Also code QL no longer runs in weekend. Running computers during weekend are fine, but getting errors isn't...
---

bugfix: CodeQL

---

.mailmap
Fitters/FitterBase.cpp
Fitters/FitterBase.h
Fitters/StatisticalUtils.cpp
Manager/Core.h

- Use GetFrom manager for default settings for skip vector for example
- Code which checks skip vector is used in several places so let's use handy function
- Getting custom LLH ranges is also in several places so let's use function
- smart pointer here and there
- Some doxygen comments here and there
---

tidy: Remove Code duplicates related to LLH scan

---

Fitters/LikelihoodFit.cpp
Fitters/MinuitFit.cpp
Fitters/MinuitFit.h
Fitters/PSO.cpp
Fitters/PSO.h

- Now minuit is smart pointer
- Added some docuemnation, in case we would like to use minuit wiht different configuration, higlhy doubt...
- Use reference in PSO for speed and safety
---

tidy: PSO and Minutit classes

---

Parameters/ParameterHandlerGeneric.cpp
Parameters/ParameterHandlerGeneric.h

Simply throw error if norm param has lower bound below 0.
---

tidy: Check Norms can't go below 0

---

Parameters/PCAHandler.cpp
Parameters/PCAHandler.h
Parameters/ParameterHandlerBase.cpp
Parameters/ParameterHandlerGeneric.cpp
Parameters/ParameterHandlerOsc.cpp

- SigmaPCA is now ErrorPCA, to be consistent with CovBase
- Move stepscale intialistion to PCA Handler
---

tidy: PCA Handler reniaming and update

---

Parameters/ParameterHandlerBase.cpp
Parameters/ParameterHandlerBase.h
Parameters/ParameterHandlerUtils.h

- Moving Matrix multiplcation helper to Utils. In princple if soemthing is in utils it can be used by toher classes.
- Adding const here and there
---

tidy: Moving Helpers from CovBase to Utils

---

Fitters/FitterBase.cpp
Fitters/FitterBase.h
Fitters/LikelihoodFit.cpp
Fitters/LikelihoodFit.h
Fitters/MinuitFit.cpp
Fitters/PSO.cpp
Fitters/mcmc.cpp
Samples/SampleHandlerBase.h
python/samples.cpp

Add virtual fucntion which allow to clean memory before fit starts
---

breaking: Before fit sanitiser

---

.github/CONTRIBUTING.md

I hear and said myself that we should restrict usage of ROOT to plotting and I/O so might as well write this explictly.
---

tidy: Update Contributing

---

Fitters/MaCh3Factory.h

Make Factory work with more than 1D
---

bugfix: Fix Facory for more than 1D

---

Fitters/FitterBase.cpp

- 2D LLH scan had no precision so bounds were huge
- Add more smart pointers to Simga Var
---

tidy: Fitter Base updates

---

Diagnostics/ProcessMCMC.cpp
Fitters/MCMCProcessor.cpp
Fitters/MCMCProcessor.h
Fitters/OscProcessor.cpp
Fitters/OscProcessor.h

This port Jarlskog from T2K repo. Original code was quite hacky so here I rmevoed quite a lot of hacks.
Two fucnionalies first just add Jarlskog to MCMCPorcessor root file. Second used output for plotting and boht adds 
Test were done using Tutorila which do not have "T2K-like" shape...
---

feat: Port Jarlskog

---

Fitters/FitterBase.cpp
Fitters/FitterBase.h

feat: SaveProposal is now configurable

---

.github/workflows/Benchmark.yml

Modify threshofl for alert for benchamrk bot
---

tidy: Modify Bot Alert threshold

---

Doc/Doxyfile
Samples/SampleHandlerBase.cpp
Samples/SampleHandlerBase.h
Samples/SampleHandlerFD.cpp
Samples/SampleHandlerFD.h

Minor improvments to docueamtion etc.
---

tidy: Imrovments to documentation

---

Fitters/MaCh3Factory.h
Samples/SampleHandlerFD.cpp

Use clone for data hist to avoid situation when on experiemnt specyfi somone deletes or ROOT autodelete histogram and MaCh3 core runs into issues
---

tidy: Clone Data

---

Diagnostics/PlotMCMCDiag.cpp
Diagnostics/README.md

…itial label
Update readme, store plot diag files in more unique way to avoid over-writing
---

feat: Diagnostics readme update and file name change

---

Fitters/FitterBase.cpp
Fitters/FitterBase.h

This bascially ports Sigma Var from T2K [SK_SigmaVar.cpp](https://github.com/t2k-software/MaCh3/blob/develop/Apps/SK_SigmaVar.cpp)
Main change with respect to T2K is different folder structure. Instead of all plots in one folder each flder is self contianed.
In T2K we had to pass custom bounds now this is being done instaed of hardcoding via config:
```
SigmaVar:
SigmaArray: [-3, -1, 0, 1, 3]
SkipVector: []
CustomRange:
prod_height:
"-3": 15.00
"-1": 15.00
"1": 15.00
"3": 15.00
```
---

feat: Sigma Var for FD

---

.github/workflows/CIBuild.yml
CMakeLists.txt
Doc/MaCh3DockerFiles/Alma9_icpx/Dockerfile
Doc/MaCh3DockerFiles/Rocky9_icpx/Dockerfile
Manager/Core.h
README.md

Simply add support for ICPX bot which will chekc compialtion
https://github.com/mach3-software/MaCh3/actions/runs/16200686401/job/45738648164?pr=551
---

feat: ICPX Bot

---

Diagnostics/ProcessMCMC.cpp

bugfix: make error message in processMCMC app a bit clearer

---

Splines/BinnedSplineHandler.cpp
Splines/SplineMonolith.cpp

- Use resize instead of push back to fight memory framganetion etc.
- Use _nCoeff_ instead of hardcdoing 4 everyhwere. We will not change this but this should make code more readable I hope
---

tidy: Reduce push back in Spline Binned

---

Parameters/ParameterHandlerBase.cpp
Parameters/ParameterStructs.h
Samples/SampleHandlerFD.cpp
Samples/SampleHandlerFD.h

IntegralList wasn't being deleted. In addition intorudce FDPlotType  to avoid magic numbers
---

bugfix: minor memory leak

---

Fitters/MCMCProcessor.cpp
Fitters/MCMCProcessor.h
Fitters/OscProcessor.cpp

Add ability to make Savage Dickey plots for Jarlskog.
All hisograms are saved so anyone can easily make whatever plot they like but want to hav some plots made by default
---

feat: Savage Dickey for Jarlskog

---

Plotting/MatrixPlotter.cpp

Previously matrix plotter was awlays printing bin conetnet. This resuted in undreadable matrices. Now it should pseudo-dynamically scale.
In addtion let;s use smart pointer
---

tidy: No longer print correlation in each bin for larger matrices

---

Fitters/FitterBase.h
Fitters/PredictiveThrower.cpp
Fitters/mcmc.cpp

- Very unlikely but if we would run SUUUPER Long chains we could reach overflow, this is supposed to prevent this
- If chain is shorter than burn in code will throw error to avoid infite loop
---

tidy: Step Number Sanitizer

---

Diagnostics/PlotMCMCDiag.cpp

Plot Diag MCMC used very oldschool C++ without proper memory managment.
Here I bascially add ton of smart pointer to make sure we are not leaking memory.
In addition use MaCh3 clone open file etc for better debbuging messages
See all plots:
[Auto_Corr_PerFile.pdf](https://github.com/user-attachments/files/21603646/Auto_Corr_PerFile.pdf)
[wacky_AccProb.pdf](https://github.com/user-attachments/files/21603648/wacky_AccProb.pdf)
[wacky_Auto_corr.pdf](https://github.com/user-attachments/files/21603649/wacky_Auto_corr.pdf)
[wacky_Average_Auto_Corr.pdf](https://github.com/user-attachments/files/21603650/wacky_Average_Auto_Corr.pdf)
[wacky_Geweke.pdf](https://github.com/user-attachments/files/21603651/wacky_Geweke.pdf)
[wacky_Trace.pdf](https://github.com/user-attachments/files/21603652/wacky_Trac …

tidy: Stop leaking in Plot Diag

---

Samples/FarDetectorCoreInfoStruct.h
Samples/SampleHandlerBase.h
Samples/SampleHandlerFD.cpp
Samples/SampleHandlerFD.h

This new struct is meant to hold info about single MaCh3 sample.
Other than helping outlod less critical fucntionality from SampleHandler this should allow in future to make multpiple samples in one object much easier.
---

feat: Sample Info

---

Diagnostics/ProcessMCMC.cpp
Fitters/MCMCProcessor.cpp
Fitters/MCMCProcessor.h

Several sanitizers
- Throw error if burn is is set too large
- If error if process MCMC yaml node is not define
- Properly set Gaussian and RMS values for fixed params
---

tidy: MCMC Processor Sanitizers

---

cmake/Modules/NuOscillatorSetup.cmake

feat: Update NuOscillator to v1.4.3

---

Diagnostics/GetPenaltyTerm.cpp
Fitters/MCMCProcessor.cpp
Manager/MaCh3Logger.h
Manager/Monitor.cpp
Manager/Monitor.h
Plotting/GetPostfitParamPlots.cpp
Plotting/plottingUtils/inputManager.cpp
Plotting/plottingUtils/inputManager.h
Plotting/plottingUtils/plottingManager.cpp
Plotting/plottingUtils/plottingManager.h
Plotting/plottingUtils/plottingUtils.cpp
Plotting/plottingUtils/plottingUtils.h
Plotting/plottingUtils/styleManager.cpp
Plotting/plottingUtils/styleManager.h

In general trying to make plotting safer (smart pointer) smarter (more default options)
- Found weird issue with debug logger, now it should correctly set it see examples to see how it owrks
[PostFitParamPlots.pdf](https://github.com/user-attachments/files/21773575/PostFitParamPlots.pdf)
[RidgePlots.pdf](https://github.com/user-attachments/files/21773576/RidgePlots.pdf)
[Test_drawCorr_Violin_Assym.pdf](https://github.com/user-attachments/files/21773577/Test_drawCorr_Violin_Assym.pdf)
---

tidy: Safer Plotting

---

Fitters/MCMCProcessor.cpp
Fitters/MCMCProcessor.h

MCMC Processor did not support applying reweighting weights for example for Reactor Constrains
---

feat: MCMC Processor support for chains with weight

---

Doc/MaCh3Web/bibliography.bib
Doc/MaCh3Web/mainpage.md
Fitters/DelayedMR2T2.cpp
Fitters/DelayedMR2T2.h
Fitters/FitterBase.cpp
Fitters/FitterBase.h
Fitters/LikelihoodFit.h
Fitters/MCMCBase.h
Fitters/MR2T2.cpp
Fitters/MR2T2.h
Fitters/MinuitFit.cpp
Fitters/MinuitFit.h
Fitters/PSO.cpp
Fitters/PSO.h
Fitters/PredictiveThrower.cpp
Fitters/PredictiveThrower.h
Fitters/StatisticalUtils.cpp
Parameters/AdaptiveMCMCHandler.cpp
Parameters/AdaptiveMCMCHandler.h
Parameters/ParameterHandlerBase.cpp
README.md
Samples/SampleHandlerBase.cpp
Samples/SampleHandlerBase.h
Samples/SampleStructs.h
python/fitters.cpp

Now Algorithm name is dynamic rather than class constant based on this thread 
https://t2k-experiment.slack.com/archives/C08MMSCFWDV/p1757663882088799
-  Several const correctness
- Add link to Indico to make people aware it exist
- fancy maths to Doxygen
- Now GetTestStat is called GetPoissonLLH because it was super confusing...
---

feat: Dynamic algorithm name

---

Splines/BinnedSplineHandler.cpp
Splines/BinnedSplineHandler.h

Replace tittle with title in BinnedSplineHandler. All others were fixed in https://github.com/mach3-software/MaCh3/pull/622
---

bugfix: more tittle -> title

---

.github/workflows/Greetings.yml
Plotting/CMakeLists.txt
Plotting/PlotSigmaVariation.cpp
Samples/SampleHandlerFD.cpp

Now that we have sigma var for FD we can make plotting.
This simple exe will loop over Sigma Var dir and make plots and there is no hard-coding whatsoever :)
[SigmaVar_Test_RatioPlots1d.pdf](https://github.com/user-attachments/files/22683202/SigmaVar_Test_RatioPlots1d.pdf)
---

feat: Sigma Var Plotting
