CMakeLists.txt, splines/gpuSplineUtils.cu
Enforces the downloading of the yaml-cpp package (https://github.com/cpm-cmake/CPM.cmake?tab=readme-ov-file#cpm_download_all). It could previously be found without being actually used.
Also adding a missing include in [splines/gpuSplineUtils.cu](https://github.com/mach3-software/MaCh3/compare/minor_fix?expand=1#diff-22d38a50e9089b009d3e907b5c38b5b4f1a9963fdb65833fb07bd228ddd87d18)
=> Minor fixes for cmake and compilation

covariance/covarianceBase.cpp, covariance/covarianceBase.h, covariance/covarianceOsc.cpp
Two small tweaks. 
- I noticed oscillation parameters weren't being given the correct priors so I've just made the prior-setter fully explicit
- delta-cp could, hypothetically be thrown outside of [-2 pi, 2pi] and not be set correctly.  I've used a bit of modular arithmetic to prevent this.
Prior Setting : 
dcp stays within the correct bounds
[dcp_trace.pdf](https://github.com/user-attachments/files/15901084/dcp_trace.pdf)
=> Feature small covariance fixes

.github/pull_request_template.md, .github/workflows/test-result-comment.yml, CMakeLists.txt, cmake/Modules/CUDASamples.cmake, cmake/Modules/CUDASetup.cmake
cmake will try to find cuda samples path, only if it find them it will add include directory etc so no more issues related to path whcih desn't exist.
If cmake cannot fidn it will CPM.
Hopefully this will put the end to cuda sample problem
using native cuda samples
using cpm ones
Printing compile options and libraries
=> Smarter CUDA Samples treatment

mcmc/MCMCProcessor.cpp
Fixes small bug where the number of flux systematics was being subtracted from ALL systematics in the MCMCProcessor printout
-> Changes MCMC processor scanning printout
Old:
```bash
[09:52:48][MCMCProcessor.cpp][info] Scanning output branches...
[09:52:48][MCMCProcessor.cpp][info] # useful entries in tree:  151  
[09:52:48][MCMCProcessor.cpp][info] # XSec params:   45 starting at 0  
[09:52:48][MCMCProcessor.cpp][info] # Flux params:   100
[09:52:48][MCMCProcessor.cpp][info] # Flux params:   100
[09:52:48][MCMCProcessor.cpp][info] # ND params:     -100 starting at 0  
[09:52:48][MCMCProcessor.cpp][info] # FD params:     -100 starting at 0  
[09:52:48][MCMCProcessor.cpp][info] # Osc params:    -94 starting at 145  
```
New:
```bash
[09:52:48][MCMCProcessor.cpp][info] Scanning output …
```
=> Fixes small bug in MCMCProcessor printout

CMakeLists.txt, cmake/Modules/MaCh3Dependencies.cmake, cmake/Modules/MaCh3Utils.cmake, covariance/covarianceBase.cpp, covariance/covarianceBase.h, covariance/covarianceXsec.cpp, covariance/covarianceXsec.h, manager/MaCh3Logger.h, manager/manager.h, mcmc/MCMCProcessor.cpp, mcmc/MCMCProcessor.h, samplePDF/Structs.h
Introduce small changes t ocmake due to changes in ROOT
- Minuit is now default, make cmake work with old as well as new ROOT cmake
- move most of dependencies to separte cmake file. For example incuions of NuOsillator will requeir modifyng MaCh3 feature list etc. Having in seperate file means main cmake is less clunky
- Add cmkae utils to reduce copy pasting
- As always documeantions
- docuemantion as always
- XsecNorm is now struct not class
- Add new fucniton GetXsecNorm, becasue SetupNormPars and GetNormParsFromDetID were like 99% the same. There are weird issues rleated with copying so we have to inilaise XsecNorm  whenever we call GetNormParsFromDetID , should be fixed in the future. But for the the time being just reduce copy pasting.
- Remove some stupid code which could cahnge …
=> Bag of tricks I learned from Luke

.mailmap, cmake/Modules/CUDASamples.cmake, manager/CMakeLists.txt, manager/Monitor.cpp, manager/Monitor.h, manager/gpuUtils.cu, manager/gpuUtils.cuh, mcmc/CMakeLists.txt, mcmc/MCMCProcessor.cpp, mcmc/MCMCProcessor.h, mcmc/gpuMCMCProcessorUtils.cu, mcmc/gpuMCMCProcessorUtils.cuh, samplePDF/kdeGpu.cu, samplePDF/kdeGpu2.cu, splines/gpuSplineUtils.cu
Allow CUDA benchamrking inspired by
https://github.com/t2k-software/MaCh3/blob/develop/check_gpu.sh
here how it looks:
=> CUDA Benchamrk

CMakeLists.txt, cmake/Templates/cmake_uninstall.cmake.in, covariance/covarianceBase.cpp, covariance/covarianceXsec.cpp, covariance/covarianceXsec.h, mcmc/SampleSummary.h, samplePDF/Structs.h
Instead of doing string comaprison whether param is spline or norm let's use enum, param types always have to be defined by MaCh3 core, I can't imagine expeirent sepcyfic types, in future types might be expadnaed, using enums helps to mainaint good code.
Also not use python like structure binding, as this causes problem in c++14. Given still many poep have root with c++14 and this was easy change I did this. MaCh3 natively should use c++14 but if we can easily mianaint c++14 then why not.
This was the issue
Setting XsecNorm4 was a mess. First we filled variables like modes, only later to save it to XsecNomr4. Now rather than have many artifialc variabels we store only XsecNorm4. This means that potetnail expansion to XsecNorms5 will be easier as everythig is handled `GetXsecNorm` rather …
=> Enum instead of string and C++14 support

manager/Monitor.cpp, manager/Monitor.h
Small check to environment variable, has more verbose crash when MaCh3 core hasn't been sourced
Small change to check MaCh3 version in `manager/Monitor.cpp`
=> Add small check to monitor so it doesn't have unhelpful crash when you haven't sourced MaCh3-core

samplePDF/samplePDFFDBase.h
Moves Bin options getter to public scope of samplePDFFDBase [no real reason for it not to be and can be useful in some applications]
=> Small Tweak to code scope

plotting/PlotLLH.cpp, plotting/PlottingConfig.yaml, plotting/plottingUtils/inputManager.cpp, plotting/plottingUtils/inputManager.h, plotting/plottingUtils/pythonPlottingModule.cpp, plotting/universalTranslator.yaml
Implemented a system for applying tags to parameters and samples for plotting. When making plots you can then loop through only parameters/samples with a given tag or set of tags. This makes it super easy to make plots for e.g. only parameters relating to pions, or only to CCQE, or only functional parameters....  
- All that's needed are a few new functions in inputManager for getting tagged values, and some maps for keeping track of the tags. 
- Tagging is now used in PlotLLH and the tags to apply can be configured in the PlottingConfig.yaml
As always, have ran using 2024 T2K Asimov:
added some vv basic tags to some of the samples
```
FGD1_numuCC_0pi_0_protons_no_photon: 
tags: ["ND280", "FGD1", "pion", "proton", "photon"]
MaCh3_ND:
LLH: "FGD1_numuCC_0pi_0_protons_no_photon" …
```
=> Feature plotting parameter tagging

.github/labeler.yml, covariance/AdaptiveMCMCHandler.cpp, covariance/AdaptiveMCMCHandler.h, covariance/PCAHandler.h, covariance/covarianceBase.cpp, samplePDF/ShiftFunctors.h, samplePDF/samplePDFFDBase.cpp, samplePDF/samplePDFFDBase.h, splines/splineFDBase.cpp
- Expand labeler
- More MaCh3 exception
- Description of PCA handler
- Remove many warning is Sample PDF FD
- pass string vector by refernce rather than copy (hopefull speed)
=> Feature tidy

covariance/covarianceOsc.cpp, covariance/covarianceOsc.h, mcmc/MCMCProcessor.cpp, mcmc/MCMCProcessor.h, samplePDF/samplePDFFDBase.cpp
Use yaml like approach for Ocs cov
If you want to test it yourself use https://github.com/mach3-software/MaCh3Validations/pull/3
- Cov osc uses yaml not root from xml converted
- Remove lot's of depracated stuff in cov osc
- Cov Osc uses not Base constructor, tl:dr all yaml reading is done VIA Base constructor, making mainaince easier
- Add baseline and denstiy as fit params. They are fixed with flat prior thus have no impact on anything
- Memory leak fixes
- Remove beta...
=> Yaml for Osc Cov

.mailmap, cmake/Modules/CUDASetup.cmake, plotting/GetPostfitParamPlots.cpp, splines/SplineMonolith.cpp, splines/SplineMonolith.h, splines/gpuSplineUtils.cu, splines/gpuSplineUtils.cuh
There was no way to pas number of GPU splines via cmake. Number of GPU splines has to be known on compiler level (annoing) but being able to at leatst pass them via cmake means we can adjsut it on experiemnt level not core level.
See it works
=> Less hardcoded GPU splines

cmake/Templates/setup.MaCh3.sh.in
if MaCh3 was installed with python module enabled then we set the PYTHONPATH environment variable in the setup script to point to the installed location. This way user doesn't need to manually set it any more.
add new function to set pythonpath variables and use it in setup.MaCh3.sh.in
N/A
=> automatically set PYTHONPATH in setup.MaCh3.sh

.github/workflows/MakeRelase.yml, Doc/sphinx/Makefile, Doc/sphinx/README.md, Doc/sphinx/make.bat, Doc/sphinx/requirements.txt, Doc/sphinx/source/conf.py, Doc/sphinx/source/index.rst, Doc/sphinx/source/mainpage.rst, Doc/sphinx/source/plotting.md, Doc/sphinx/source/plotting.rst, Doc/sphinx/source/pyMaCh3.rst, README.md, plotting/plottingUtils/pythonPlottingModule.cpp
Add in ability to generate sphinx documentation for the pyMaCh3 module
added all necessary configs and some instructions on how to build to the readme
Behold
Marvel at its beauty
=> Sphinx documentation for python

.github/workflows/CDImage.yml, .github/workflows/CIBuild.yml, .github/workflows/CIValidations.yml, CONTRIBUTING.md, README.md, covariance/covarianceBase.cpp, covariance/covarianceBase.h, manager/YamlHelper.h, mcmc/FitterBase.cpp, mcmc/FitterBase.h, mcmc/MCMCProcessor.cpp, mcmc/MCMCProcessor.h
This allow to streamline many things.
Now when using MCMC Processor it load yaml from MCMC instead of loading one from computer
Ideally in future we should have Covaraince class cosntructor which gets Yaml node
=> Save Covariance in MCMC File

cmake/Templates/setup.MaCh3.sh.in
These [ $d == "blarb" ] conditions are correctly evaluated only in bash. To allow for other shells, you need one of these:
if [ $d = "blarb" ]; then
or
if [[ $d == "blarb" ]]; then
=> fix to work with other shells than bash

.github/workflows/Doxygen.yml, Doc/mainpage.md
"These will be automatically generated. It should be pretty easy to get working" - Me on Monday. Well here we 15 commits and dozens of failed attempts later. But... it works!
Extend the documentation generation action to also build sphinx documentation for python and add it to a sub folder in the existing html which gets uploaded to github pages. 
One note is that it now takes a bit longer to generate as it needs to actually build the python module in order to make the documentation for it. In future it might be good to have it only run the sphinx generation part if the python code has been changed (this is tricky but I think not impossible to do). Or only generate new documentation only on tags rather than every PR.
=> Auto generation python docs

.github/workflows/Doxygen.yml
Just one more PR man, then I'm done for good, I swear
I broke gh-pages branch by uploading an empty directory because the actual html wasn't making it to the "deploy" job
=> Fix gh-pages deployment

covariance/covarianceBase.cpp, covariance/covarianceBase.h, covariance/covarianceOsc.cpp, covariance/covarianceOsc.h, covariance/covarianceXsec.cpp, covariance/covarianceXsec.h, mcmc/FitterBase.cpp, mcmc/FitterBase.h, mcmc/LikelihoodFit.cpp, mcmc/mcmc.cpp, python/fitter.cpp, samplePDF/samplePDFFDBase.cpp, splines/splineFDBase.cpp
WARNING, this will break DUNE! 
Changes here are not backward compatibilte
- We no longer need special treatment for cov osc in fitter base. Now cov osc should be added same way as any other systematics
- Stop with terrbile hardcdoing of fixing baseline etc
- stop using const char, we should do this long time ago
- Remove many getter in cov osc, we should enforce using new more gnereir getters
=> Remove Garbage

.github/workflows/CIValidations.yml, CMakeLists.txt, covariance/covarianceBase.cpp, mcmc/FitterBase.cpp, mcmc/FitterBase.h, mcmc/LikelihoodFit.cpp, mcmc/MCMCProcessor.cpp, mcmc/PSO.cpp, mcmc/PSO.h, mcmc/StatisticalUtils.h, plotting/CMakeLists.txt, plotting/MatrixPlotter.cpp, plotting/README.md, samplePDF/Structs.cpp, samplePDF/Structs.h, samplePDF/samplePDFBase.cpp
Move Matrix Plotter from T2K. This is example of plots using tutorial chain
https://github.com/mach3-software/MaCh3Tutorial/blob/3b0851a4fdb86000dc37ae1106cf0ac0db63342f/Tutorial/TutorialDiagConfig.yaml#L115C1-L127C4
- Continute throwing smart pointers/vector and c++ casting whenever I can
- Moving some statistical utils from T2K
- Changed identation in PSO
- Matrix Plotter to CI
- More logger
- Moved MakeAsymGraph from Fitter Base, this is fucntion is gnereic enough than deosn't have to be in FitterBase
[MatrixPlot.pdf](https://github.com/user-attachments/files/17533378/MatrixPlot.pdf)
=> Matrix Plotter

python/samplePDF.cpp, samplePDF/CMakeLists.txt, samplePDF/FarDetectorCoreInfoStruct.h, samplePDF/samplePDFFDBase.cpp, samplePDF/samplePDFFDBase.h, splines/splineFDBase.cpp
Mainly tidying up some bits of code especially the FarDetectorStruct class. Removing allocation of lots of arrays on the heap to use std::vectors instead. Also a general bit of tidy up here and there.
Rename of FDMC struct to FarDetectorStruct. Also moving many of the members of this struct to be vectors. Small clean up of splineFDBase class.
e.g. int* modes = new int[nEvents]; -> std::vector<int> modes; modes.resize(nEvents);
=> Feature tidy up

.github/CONTRIBUTING.md, CMakeLists.txt
=> adds -DMaCh3_WERROR_ENABLED=OFF options if you just can't even with GCC

.github/workflows/CIValidations.yml, CMakeLists.txt, README.md, cmake/Modules/CUDASamples.cmake, cmake/Modules/CUDASetup.cmake, cmake/Modules/NuOscillatorSetup.cmake, manager/gpuUtils.cuh
Patch to ensure MaCh3 compiles on GPU again
- Changes remaining `MaCh3CompilerOptions` to `MaCh3CompileDefinitions` in `CUDASamples.cmake` and `CUDASetup.cmake`
- Changes to using `NuFastLinear` by default as `CUDAProb3` will no longer compile
- Ignores errors on` #include <cuda_runtime.h>` as it still has C-style casts https://github.com/mach3-software/MaCh3/blob/f511bc15f8adc8c3d7791c90230eeb5a6a6fca68/manager/gpuUtils.cuh#L10-L13
=> Fix CUDA compilation

Diagnostics/RHat.cpp
Fixes [https://github.com/mach3-software/MaCh3/security/code-scanning/2135](https://github.com/mach3-software/MaCh3/security/code-scanning/2135)
To fix the problem, we need to ensure that the multiplication is performed using a larger integer type to prevent overflow. We can achieve this by casting one of the operands to `size_t` before performing the multiplication. This will promote the multiplication to `size_t`, which has a larger range than `int`.
- Change the multiplication `Ntoys * Nchains` to `(size_t)Ntoys * Nchains` to ensure the multiplication is done using `size_t`.
- This change should be made on line 330 in the file `Diagnostics/RHat.cpp`.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 2135: Multiplication result converted to larger type

Diagnostics/RHat.cpp
Fixes [https://github.com/mach3-software/MaCh3/security/code-scanning/2136](https://github.com/mach3-software/MaCh3/security/code-scanning/2136)
To fix the problem, we need to ensure that the multiplication is performed using the larger integer type (`Long64_t`) to avoid overflow. This can be achieved by casting one of the operands to `Long64_t` before performing the multiplication. This way, the multiplication will be done using the larger type, and the result will be correctly stored in the larger type.
Specifically, we will cast `Ntoys` to `Long64_t` before multiplying it by `Nchains` on line 304. This change will ensure that the multiplication is performed using `Long64_t`, preventing any overflow issues.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 2136: Multiplication result converted to larger type

mcmc/MCMCProcessor.cpp, mcmc/PSO.h
Fixes to compile with werror flag enabled
- PSO used std::bind1st which is deprecated, now has std::bind implementation
- makes sure system flags warning (to get around unused variable!)
=> More fixes to werror

CMakeLists.txt, covariance/covarianceXsec.cpp, covariance/covarianceXsec.h
Luke made comment that we should be case isnetivive for parmaeter group.
Added small fucntion to redcue of copy pasting some code related with DetId. This should make even simpler modyfign treatment in the future.
=> Caseinsentisitve param group

mcmc/PSO.cpp, mcmc/PSO.h, mcmc/SampleSummary.cpp, mcmc/SampleSummary.h, plotting/CMakeLists.txt, plotting/GetPostfitParamPlots.cpp, plotting/MatrixPlotter.cpp, plotting/PlotLLH.cpp
- PSO didn't have any logger
- Luke haven't finshed tidy of plotting exe. Here is my attempt
=> Random Tidy

Doc/sphinx/source/covariance.rst, Doc/sphinx/source/fitter.rst, Doc/sphinx/source/manager.rst, Doc/sphinx/source/plotting.rst, Doc/sphinx/source/sample-pdf.rst, Doc/sphinx/source/splines.rst
I didn't update the sphinx doc source to be aware of the new module structure. Should hopefully work now
=> fix the links in sphinx docs

.github/workflows/CIValidations.yml, plotting/plottingUtils/inputManager.h
Fixed some issues I had with plotting, now it should work correctly so addign it as part of CI
=> Fix plotting

.github/workflows/CIPythonValidations.yml, CMakeLists.txt, Doc/Doxyfile, Doc/MaCh3DockerFiles/Ubuntu22.04/Dockerfile, covariance/covarianceBase.cpp, covariance/covarianceBase.h, plotting/GetPostfitParamPlots.cpp
- Now we can PCA second cov base cosntuctro
- For ridge plot we can grab actual posterior instead of taking primitve
- PostfitHistVec somehow wasn't filled :( which was casuing problems
=> Some Fixes

mcmc/MCMCProcessor.cpp
Michael pointed out that Rhat cachinw. Same code is used in Mg is sloCMC Processor. In inital test caching was dropped from 1.4s to 0.4s [see plots below]
amples
=> Faster caching

.github/workflows/PRtittleChecker.yml, samplePDF/FarDetectorCoreInfoStruct.h, samplePDF/samplePDFFDBase.cpp, samplePDF/samplePDFFDBase.h, splines/splineFDBase.h
Makes the option to use the low memory structs more reliable. Any function in samplePDFFDBase or splineFDBase now is of type M3::float_t so it will change depending on whether _LOW_MEMORY_STRUCTS_ is defined.
Also a small tidy up to remove some duplicated definitions of Unity.
- fix: Now use M3::float_t type in various functions where we want the weight to be a float or a double.
- tidy: Removing Unity and dummy value definition from the FarDetectorCoreInfo struct since there is also a definition in samplePDFFDBase.h
=> bugfix: Now use M3::float_t type in more places, tidy: Removing duplicated Unity values

CMakeLists.txt, cmake/Modules/NuOscillatorSetup.cmake
CPU flags weren't proapgted correctly to NuOsc after:
https://github.com/mach3-software/MaCh3/pull/237
before:
after:
=> bugfix: Fix flag proapgation to NuOsc

covariance/AdaptiveMCMCHandler.cpp
Changes Settings->Covariance when looking for matrix blocks in the adaptive MCMC settings
=> Breaking: Corrects setting in adaptiveMCMC handler which causes crashes

covariance/covarianceBase.cpp, covariance/covarianceBase.h
This is not used anymore so delete
=> breaking: Remove Legacy init

CMakeLists.txt, Diagnostics/CombineMaCh3Chains.cpp, Doc/Doxyfile
Problem has been outlined here:
https://github.com/mach3-software/MaCh3/pull/246
tl:dr now combine MCMC ignore stuff like different chain names
Proof that it works"
=> feat: Smarter CombineMCMCChains

covariance/covarianceBase.h
=> tidy: Setters and Getters for updted Covariance CI

.github/workflows/CIValidations.yml, Doc/bibliography.bib, covariance/AdaptiveMCMCHandler.h, covariance/PCAHandler.h, covariance/covarianceBase.cpp, covariance/covarianceBase.h, mcmc/FitterBase.cpp, plotting/plottingUtils/inputManager.cpp, plotting/plottingUtils/inputManager.h
We often use defined step scale. However we know based on literature what it should be. Now simply throw warning if step scale is very different. This should help spot mistakes.
- No longer have to covnert const char to string in adaptive code
- Now default error is 1 not 0. error being 0 can be interpeted as fixed param and we don't want this
- remove a lot of blank line in plotting
- raw pointer -> std::vecotr in cov
- more bibliography (hope is usefull)
- use new LLH scan bot
=> tidy: Step Scale Sanity chekc et. al.

plotting/GetPostfitParamPlots.cpp
Same config syntax as for param overlay now works for violin plot. Code might requier some tidy in future but genral feature is giving us missing previously flexbility. No longer we hardcode T2K stuff...
[Test_drawCorr_Violin_Assym.pdf](https://github.com/user-attachments/files/18154159/Test_drawCorr_Violin_Assym.pdf)
=> feat: Flexible Violin Plotter

mcmc/FitterBase.cpp, samplePDF/FarDetectorCoreInfoStruct.h, samplePDF/Structs.h, samplePDF/samplePDFBase.cpp, samplePDF/samplePDFBase.h, samplePDF/samplePDFFDBase.cpp, samplePDF/samplePDFFDBase.h
Minor tidy of sample pdf
- dataSample was pointer to vector... this is terrible... I am speachless... either way it wasn't use so removed
- We were resetting histogram in ResetHistohgram and in FillArray now we do this once
- Remove lot of legacy stuff from PDF base
- Moved unityf to struct instead as meber of SamplePDF
- reuturn at the end of void is just noise
Nothing critical so I don't think valdiations other than bots are neccessary
=> tidy: Janitorial work for SamplePDF

covariance/covarianceXsec.cpp
`norm_index `were not bein updated if param was not affected by det id. This meant that we were getting offset of params. Now we use map so everyhting should be fine
In T2K this resulted in one of ND280 flux params not affectin ND280
before
```
[samplePDFND.cpp][info] ND280 Normalisation parameters: 70
[samplePDFND.cpp][info] ===============================================================
[samplePDFND.cpp][info] 67   |  233        |  b_46                                     | 
[samplePDFND.cpp][info] 68   |  234        |  b_47                                     | 
[samplePDFND.cpp][info] 69   |  235        |  b_48                                     | 
[samplePDFND.cpp][info] ===============================================================
```
after:
```
[samplePDFND.cpp][info] 65   | …
```
=> bugfix: Update treatment of getting Norm Params

manager/CMakeLists.txt, mcmc/MCMCProcessor.h, mcmc/StatisticalUtils.h, samplePDF/CMakeLists.txt, samplePDF/HistogramUtils.cpp, samplePDF/HistogramUtils.h, samplePDF/Structs.h, samplePDF/samplePDFBase.h
There were plneey of histogram related utils in Structs. This was cofnusing so now stucts are actual headers and all other fucnitons have been moved to Histogram Utils
Alos modified name of one function to make it properly compiled
=> tidy: Make Structs actual Structs

.github/workflows/Benchmark.yml, README.md
For more see: https://github.com/mach3-software/MaCh3Tutorial/pull/68
=> feat: Continous Benchmarking

Diagnostics/README.md, covariance/covarianceBase.cpp, covariance/covarianceBase.h, covariance/covarianceOsc.cpp, covariance/covarianceOsc.h, covariance/covarianceXsec.h, python/covariance.cpp
Plenty of tidy to cov classes
- With NuOsc we no longer need hacks for baseline and desnity
- Stop with hardcoded checks for Sin for bounds, use actual base check bounds
- We still have special tramtent from ordering so added warning if these are not defined
- Removed some other dpecracated stuff from other covs
=> breaking: Less stinky Cov Osc

samplePDF/CMakeLists.txt, splines/CMakeLists.txt
This is problem
```
/usr/bin/ld: ../_deps/mach3-build/splines/libSplines.so: undefined reference to covarianceXsec::GetSplineParsNamesFromDetID[abi:cxx11](int)'
/usr/bin/ld: ../_deps/mach3-build/splines/libSplines.so: undefined reference to covarianceXsec::GetSplineInterpolationFromDetID(int)'
/usr/bin/ld: ../_deps/mach3-build/splines/libSplines.so: undefined reference to covarianceXsec::GetGlobalSystIndexFromDetID(int, SystType)'
/usr/bin/ld: ../_deps/mach3-build/splines/libSplines.so: undefined reference to covarianceXsec::GetNumParamsFromDetID(int, SystType)'
/usr/bin/ld: ../_deps/mach3-build/splines/libSplines.so: undefined reference to covarianceXsec::GetSplineModeVecFromDetID(int)'
```
Problem is Splines depend on Covariance, so had to change linking order. Porblem only appeared for …
=> bugfix: linking splines on ubuntu

manager/MaCh3Logger.h
Simply if for some reason we can't redirect buffer then do not attempt to do this
=> Tidy: safer logger

Diagnostics/CombineMaCh3Chains.cpp
`<unistd.h>` is required for `getopt`, `optind`, and `optarg`. It seems with older ROOT versions, it may be included here indirectly, but will give compilation errors on newer versions.
Explicitly including it shouldn't change any behavior, and make MaCh3 compile on more environments.
=> bugfix: Add missing unistd.h include for newer ROOT versions

samplePDF/samplePDFFDBase.cpp, samplePDF/samplePDFFDBase.h
None of current experiemnt get weight from from func pars. Current implemntaiton requeprs at least one mutliplication per event. Mutliplication by 1 does nothing for physics but does impact perofmacne.
New implemation retain feasiblity to apply func weights but doesn't suffer for peromance issue.
Need this to work:
https://github.com/mach3-software/MaCh3Tutorial/pull/73
=> breaking: Alter treamtent of getting weight from func pars

cmake/Modules/NuOscillatorSetup.cmake, manager/MaCh3Logger.h
Issue was found where if an error occurred in NuOscillator, the new fancy logging system wouldn't post the output to the console so the error was very difficult to solve. Now catch any runtime error and redirect stringstream buffer to console so error can printed to screen
=> bugfix: Print output from MaCh3Logger fancy logging function if error is thrown

manager/Monitor.cpp, mcmc/MaCh3Factory.cpp, mcmc/MaCh3Factory.h
New manager factory inspired by random chat with Henry some time ago.
Main motivation is to allow override config via comand line.
Normally one would have to change config to change filename.
This feature allow to do stuff like this
`./bin/MCMCTutorial Inputs/FitterConfig.yaml General:OutputFile:blarb.root`
Which should be super handy if running running batch jobes
Warning after Dan't comment
=> feat: Manager Factory

samplePDF/HistogramUtils.h
Removed a reference to TLorentVector as it is now a legacy class and doesn't work with ROOT version 6-32-08. 
Info here: https://root.cern.ch/doc/master/classTLorentzVector.html
=> bugfix: Remove a reference to TLorentzVector

samplePDF/FarDetectorCoreInfoStruct.h, samplePDF/samplePDFFDBase.cpp, samplePDF/samplePDFFDBase.h
Previous treatment of reading the 'signal' variable from the sample config was not being done in the core code. This meant that it was always false. Consequently (unless it was specifically filled in experiment specific code), NC signal events were being applied an oscillation weight. This will likely result in a small event rate change.
*** Relies upon https://github.com/mach3-software/MaCh3/pull/293 being merged first ***
Rather than rely upon signal variable, just directly check the nupdg and nupdgUnosc variables are the same. Consequently can remove the signal entry from sample configs.
=> bugfix: Correctly read Signal FDMC variable from config

CMakeLists.txt, Doc/Doxyfile, covariance/covarianceBase.cpp, covariance/covarianceBase.h, covariance/covarianceOsc.cpp, covariance/covarianceOsc.h, covariance/covarianceXsec.cpp, covariance/covarianceXsec.h, samplePDF/FarDetectorCoreInfoStruct.h, samplePDF/Structs.h, samplePDF/samplePDFFDBase.cpp, samplePDF/samplePDFFDBase.h, splines/splineFDBase.cpp, splines/splineFDBase.h
See also: https://github.com/mach3-software/MaCh3Tutorial/pull/71
Instead of hardcoded names let's have string:det id
Sample PDF can only have 1 string, and no wildcards
However now each syst can have several "det ids" to which applies"
For example     **DetID: ["Tutorial *"]** or    **DetID: ["Tutorial *", "Blarb *"]**
In addition now DetId applies to Osc params. For example delta CP will aply to all but baseline only to beam.
You can see in this example that parameters with **DetID: ["Tutorial *"]**
```
Found 3 for Tutorial Beam Params of type Norm
Found 5 for Tutorial Beam Params of type Spline
Found 4 for Tutorial Beam Params of type Functional
Found 3 for Tutorial Beam From GetNormParsFromDetID
Found 3 for Tutorial ATM Params of type Norm
Found 5 for Tutorial ATM Params of type …
```
=> breaking: Improve Det Id tremtent

samplePDF/samplePDFFDBase.cpp, splines/splineFDBase.cpp
Fix where throw is launched from in splineFD dimension checking and remove obnoxious console output
=> bugfix: Move throw to within expected if statement in splineFDBase dimension checking

samplePDF/samplePDFFDBase.cpp, splines/splineFDBase.cpp, splines/splineFDBase.h
The loggers in SplineFDBase showed some redundant and unclear information. I tidied it up a bit while preserving necessary printouts.
- Merge PrintArrayDetails and PrintArrayDimensions functions and remove the latter
- Update SamplePDFFDBase after this change.
Before the fix, splineFDBase would show this output:
And after the update, it shows this:
=> feat: Improve spline printouts and remove redundancies

cmake/Templates/setup.MaCh3.sh.in
Tiny tweak python path include to match all other add to path we have in setup
=> tidy: Update python path include

samplePDF/Structs.h, splines/splineFDBase.cpp, splines/splineFDBase.h
Code should be nicer and faster (by small margin...)
- vector -> const vector& for speed
- Made templates to more easily clean std::vectors
- Binning wasn't properly deleted
- Find spline segment was making parraler but didn't use for, waste of resources...
- In find spline segment xArray was copied... waste of resources...
- lot of const for const corecctens...
- introduce `coeffOffset` to avoid multiplciation by 4 so many times...
- SetupSplines wasn't used so removed
- addef fmaf_t to avoid total mess in calcsplinewieght...
=> tidy: Janitorial work for SplineFD

mcmc/FitterBase.cpp, mcmc/FitterBase.h, mcmc/mcmc.cpp, mcmc/mcmc.h
A few tweaks to have the chain restart working
- Moved stepStart to `FitterBase` to be able to quote the right time per step
- Fixed some inverted nullptr condition
- Fixing some write to deleted memory space by resetting the branches after the previous systematics have been read.
=> Bugfix: chain restart fix

samplePDF/samplePDFFDBase.cpp
PrepFunctionalParameters is virtual so it is unpredicatbale what expriemnt will perofrm there,  while in spline Evaluate there are parraler operations. 
Having multiple parraler region may be fine and may not be fine (highly dpend on framwork). It is safer to move away these oepration away from parraler region
=> tidy: Move Spline Eval Away from parraler region

covariance/PCAHandler.cpp, covariance/PCAHandler.h, covariance/covarianceBase.cpp, covariance/covarianceBase.h, covariance/covarianceXsec.cpp, manager/Monitor.cpp, manager/Monitor.h
Simply move as much as possible stuff from Covariance to PCA Handler to make code easier to follow.
=> tidy: Reorganisation of PCA Handler

covariance/covarianceBase.cpp, covariance/covarianceBase.h, manager/Core.h, splines/SplineBase.cpp, splines/SplineBase.h, splines/SplineMonolith.cpp, splines/SplineMonolith.h, splines/SplineStructs.h, splines/splineFDBase.cpp
Genrally  destructors should be virtual
- Virtual destructors
- Now NoExpect should work correctly
- stop with manual delting std::vectors
=> tidy: Proper descturctors for spline related classes

mcmc/CMakeLists.txt, mcmc/MCMCProcessor.cpp, mcmc/MCMCProcessor.h, mcmc/OscProcessor.cpp, mcmc/OscProcessor.h
MCMC Processor is cool class for genral MCMC plotting. However Osc params requeir plenty of hard coding. 
Idea is that this class will deal with all nast hardcdoging like Unitarity Triangles, Jarlskog etc which make no sense for rest of params.
Since OscParams Inherit from MCMC Processor it should be possible to resuse tools.
This is first version. In T2K we still have plenty of fucntionality that should be ported.
In addtion itroduced minor tidy
=> feat: First Version of Osc Processor

CMakeLists.txt, manager/Core.h, manager/YamlHelper.h
`cmake ../ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++`
I was able to compile MaCh3 using clang. 
I am not sure wheter we want support mutliple compilers (clang is easy as can be used on linux and terafore bots)
To make it work I had to introduce minor changes so might be worth making our build systeamt more robust.
I know peoplle were intereted in Intel compiler (this one is more difficutl to test) that's why I played with muktiple compiler support
=> feat: Initial support for clang

splines/splineFDBase.cpp
isflatarray is an array, use `delete []` rather than `delete`
=> bugfix: delete -> delete [] for isflatarray

cmake/Modules/NuOscillatorSetup.cmake
Allow option to use alternative NuOscillator branches:
```
[barrowd@pplxint12 build]$ cmake .. -DMaCh3_NuOscillatorBranch="feature_NuSQUIDS" -DCUDAProb3_ENABLED=ON
...
-- CPM: Adding package NuOscillator@1.2.0 (feature_NuSQUIDS)
-- [INFO]: NuOscillator Features: 
-- [INFO]:      CUDAProb3: 1
-- [INFO]:      CUDAProb3Linear: 0
-- [INFO]:      Prob3ppLinear: 0
-- [INFO]:      ProbGPULinear: 0
-- [INFO]:      NuFASTLinear:  0
-- [INFO]:      NuSQUIDSLinear: 0
-- [INFO]:      OscProb: 0
-- [INFO]: Required variables being used:
-- [INFO]: 	Not using GPU
-- [INFO]: 	Using Multithreading with nThreads=128
```
```
[barrowd@pplxint12 build]$ cmake .. -DCUDAProb3_ENABLED=ON
...
-- CPM: Adding package NuOscillator@1.2.0 (v1.2.0)
-- [INFO]: NuOscillator Features: 
-- [INFO]:      CUDAProb3: 1
-- …
```
=> feat: Add cmake option to be able to pass which NuOsc branch to build against

mcmc/FitterBase.cpp
This is just a small update to https://github.com/mach3-software/MaCh3/pull/346 where the LLHScanSkipVector was being searched under General node in the Sigma Variation function.
=> bugfix: LLHScanSkipVector yaml node group inside sigma variation function

covariance/covarianceOsc.cpp
As discussed in `#mach3_crossexperiment` on Slack, turn MO switching on by default, leaving the ability to switch it off with `setFlipDeltaM23` is desired.
(Fixed version of #377 to avoid CI problem)
=> feat: Turn on MO switching by default

Diagnostics/ProcessMCMC.cpp, mcmc/MCMCProcessor.cpp
Initialize burn in cut to 0, and set it from YAML file in `ProcessMCMC`, instead of hardcoding it to 1/5.
=> feat: Set Burn-In from YAML file

covariance/covarianceOsc.cpp
This fixes a few problems with `CircularPrior()` (used for delta_cp).
First, e.g. with delta_cp, this won't actually be cyclical with period 2pi, but with period pi. For example, we want 2.5pi -> 2.5pi - 2pi = 0.5pi. But currently, this sends 2.5pi -> -pi + 0.5pi = -0.5pi.
Second, the logic is broken and won't generalize to things besides delta_cp. The signs of the `fmod` terms will be the wrong sign if `UpBound` is less than zero, or if `LowBound` is more than zero. Also, if one of the two bounds is zero, you'll get a divide by zero error.
=> bugfix: Fix CircularPrior logic

samplePDF/samplePDFFDBase.cpp
Because of the EqualBinningPerOscChannel handling, binned osc configuration and switching between binned and unbinned oscillation calculation for NuOscillator are unnecessary difficult to be set properly.
EqualBinningPerOscChannel comes from sample configuration (multiple configuration files) and serves as a "sort of an indicator" of binned oscillation weights for samplePDFFDBase  (see `samplePDFFDBase::SetupNuOscillator()`). But, the calculation type is set in NuOscillator. As a result, to effectively switch between different calculation types, one needs to edit multiple configuration files, which is rather bacwardy. I would prefer handling the calculation type from NuOscillator config directly.
Not sure whether this might be called a bug or a user experience feature:)
I suggest checking …
=> feat: Override EqualBinning setting when not using binnedosc

covariance/covarianceBase.cpp, covariance/covarianceBase.h, covariance/covarianceOsc.cpp, covariance/covarianceOsc.h, covariance/covarianceXsec.cpp, covariance/covarianceXsec.h, mcmc/FitterBase.cpp, mcmc/MaCh3Factory.h, samplePDF/samplePDFBase.h, samplePDF/samplePDFFDBase.cpp, samplePDF/samplePDFFDBase.h, splines/splineFDBase.cpp, splines/splineFDBase.h
Instead of reading in a separate field "DetID" from a sample config instead the "SampleName" is used and a separate field of "SampleTitle" has been added so that it can be used for plotting names.
This addresses this issue: https://github.com/mach3-software/MaCh3/issues/373
Renaming of covariance class functions where I felt it was appropriate to use SampleName rather than DetId.
samplename is now SampleTitle and samplePDFFDBase::GetName is samplePDFFDBase::GetTitle
SampleDetID is now SampleName.
DetID in parameter yaml is now SampleID
Additional check in FitterBase on whether the SamplePDF object has a unique name.
CovarianceXsec::AppliesToDetID -> CovarianceXsec::AppliesToSampleName
=> breaking: det id fix

mcmc/FitterBase.cpp
I believe these histogram and LLH calculation indices are wrongly iterated over. Histograms reserved for LLHs of `samples[0]` (corresponding to the first `samples[0]->GetNsamples()` of `TotalNSamples` histograms) are being overwritten with LLHs from samples of `samples[ivs]`. We need `SampleIterator` index in here.
Also, is there some logic or reason why to iterate over `samples` and `samples[ivs]` (indices `ivs` and `is`) and not simply from 0 to `TotalNSamples` (see also at least one other loop in `RunLLHScan()`, where no `ivs` and `is` are used)? Like this:
```
for(unsigned int is = 0; is < TotalNSamples; ++is )
{
hScanSamSplit[is]->SetBinContent(j+1, 2*sampleSplitllh[is]);
}
```
Insert `SampleIterator` index instead of `is` , which runs again from 0 for each `samples[ivs]`.
=> bugfix: fix the index of sample llh histograms

CMakeLists.txt
CMakeLists.txt had a typo that didn't allow CUDA to be included if GPU was enabled. 
Changed line if(CUDAToolkit_FOUND AND NOT(MaCh3_GPU_ENABLED)) to if(CUDAToolkit_FOUND AND MaCh3_GPU_ENABLED).
=> bugfix: Fix typo to make CUDA work properly

splines/splineFDBase.cpp
On knot spline eval and Y value should be the same. We can skip spline eval part (this include alos find spline segment).
This make spline loading 5-10% faster.
before:
```
[splineFDBase.cpp][info] Number of combinations of Sample, OscChan, Syst and Mode which have entirely flat response: 2694051 / 2760858
[splineFDBase.cpp][info] Total number of splines loaded: 2760858
[splineFDBase.cpp][info] Total number of non-flat splines loaded: 66807
[splineFDBase.cpp][info] Now transferring splines to a monolith if size 2760858
[samplePDFFDBase.cpp][info] --------------------------------
[samplePDFFDBase.cpp][info] Setup Far Detector splines
[splineFDBase.cpp][info] Cleaning up spline memory
[samplePDFFDBase.cpp][info] It took 415.0200 s 
```
after
```
[splineFDBase.cpp][info] Number of …
```
=> feat: Faster Spline Loading

python/samplePDF.cpp, samplePDF/samplePDFBase.cpp, samplePDF/samplePDFBase.h, samplePDF/samplePDFFDBase.cpp, samplePDF/samplePDFFDBase.h
Fixing a clashing treatment of SampleNames in samplePDFFDBase and samplePDFBase. Removed SampleNames std::vector from samplePDFBase and made GetSampleNames to be pure virtual. All base classes are currently over-riding this function anyway.
- Removing std::vector<std::string> SampleNames from samplePDFBase
- Making GetSampleNames(int iSample) pure virtual so you have to specify how to get the sample name.
- Changing GetName to GetSampleName(int iSample=0) in samplePDFFDBase which isn't ideal as iSample is not used in this function.
=> feat: get sample name fix

.gitignore, covariance/covarianceXsec.cpp, covariance/covarianceXsec.h, python/samplePDF.cpp, samplePDF/Structs.h, samplePDF/samplePDFFDBase.cpp, samplePDF/samplePDFFDBase.h
Added an implementation of functional parameter that's hopefully faster and more flexible. 
- Added a new struct `FuncPars` in Structs.h, similar to spline and norm. 
- This struct will take a valuePtr and a funcPtr. The former is set by `covarianceXsec::GetFuncPars` and the latter is set by `samplePDFFDBase::SetupFunctionalParameters`. 
- In samplePDFFDBase, added `applyShift`, `SetupFunctionalParameters`, `RegisterIndividualFuncPar`.
-  `RegisterFunctionalParameters` and `resetShift` are virtual so they need to be implemented in inherited classes. 
A demo can be found in the [MaCh3 tutorial](https://github.com/mach3-software/MaCh3Tutorial/tree/hhua/demo/FunctionalParams) by running:
```
build/bin/KinemDistributionTutorial ./TutorialConfigs/FitterConfig.yaml
```
=> feat: functional parameters

manager/manager.cpp, samplePDF/HistogramUtils.cpp, samplePDF/samplePDFBase.cpp, samplePDF/samplePDFFDBase.cpp, samplePDF/samplePDFFDBase.h
Previously test statictic was being set via
`fTestStatistic = static_cast<TestStatistic>(SampleManager->raw()["TestStatistic"].as<int>());
`
which was simply wrong... this didn't work.
The only reason why it worked is becasue this yaml node was not set so it was defaulting to Poisson.
Now selection should work.
In addition add option to not update W2 based on T2K expierences.
=> bugfix: Properly select test statistic

manager/YamlHelper.h, manager/manager.cpp, manager/manager.h
Give ability to merge yaml configs, in near future I want to have ability of overwriting configs.
For example you have base T2K config, and ATM config with additional settings. You could pass both and MaCh3 would simply add/overwrite settings. For valdiations see: https://github.com/mach3-software/MaCh3Tutorial/pull/110
Also add new constuctor for manager to make easier to start from previous chain (changes will have to be done on exe level)
=> feat: Yaml Merging

covariance/covarianceBase.cpp, manager/Core.h, manager/YamlHelper.h, samplePDF/samplePDFFDBase.cpp, samplePDF/samplePDFFDBase.h
This is meant to help having to specify bounds like
```
SelectionCuts:
- KinematicStr: "RecoLeptonMomentum"
Bounds: [100., 1000000.]
```
and instead use ""
like here:
SelectionCuts:
- KinematicStr: "RecoLeptonMomentum"
Bounds: [100., ""] 
In addition found std::vector< std::vector<double> > SelectionBounds; is not used at all so remvoed it. Did check both T2K and DUNE and neither uses it.
test with wrong size
test with wrong string
test with upper bound
test with both bounds (pointless but why not...)
Test that everything works as it used to be
=> feat: Ability to speicfy "empty" bounds

manager/Monitor.cpp
Previously there was no way to run wiht more 16 threads other than commenting out line.
Simplest way to still have error (which I think is usefull for less expirenced users) but give ability to play with for more expireinced is to make check based on OMP_NUM_THREADS enviorment
=> bugfix: Improve Thread Sanity

cmake/Templates/setup.MaCh3.sh.in
1. Use [[ ]] instead of [ ] as the latter has bash specific evaluation, different in modern bash-like shells. See the diffs of [[ , [, (, ((, e.g. [here](https://unix.stackexchange.com/questions/306111/what-is-the-difference-between-the-bash-operators-vs-vs-vs). Alternatively, if [ ] is to be used, the conditions shall be recast to work properly, there are proper POSIX [ ] equivalents for any [[ ]].
2. Allowing a universal (shell-inclusive) and path-independent setup of MaCh3 based on the location of the setup.MaCh3.sh script.
Switch for an implementation piece that would allow for locating the script and defyning the MaCh3_ROOT path, irrespective of where the setup script is called from, with equivalent output in a number of different shell types.
Including examples from a script …
=> feat: Universal, path-independent setup

python/samplePDF.cpp, samplePDF/Structs.h, samplePDF/samplePDFFDBase.cpp, samplePDF/samplePDFFDBase.h
Instead of passing vector of doubles simply use new struct for applying kinematic cuts. I personally didn't like how we were casting  double to enum. Passing int to enum is faster and safer (no need of floating operations).
Marked as breaking as ReturnKinematicParameter now uses `int `not `double`
Merge this before: https://github.com/mach3-software/MaCh3Tutorial/pull/115
- Removed enums related to Prob3++ (NuOsc is handling this)
- NSelections and SplineBinnedVars wasn't used anywhere (checked T2K and DUNE codes as well)
---
=> breaking: Add Kinematic Cut Struct

cmake/Templates/setup.MaCh3.sh.in
Trying to edit the setup functions to be portable and sourceable across different unix shells. I tested this version with bash, sh, zsh, ksh, and dash. This script can be sourced from anywhere, independent on your current $(pwd).
Unfortunately, this is cannot be sourced in csh and tcsh shells. Likely a specific script is needed (though I hope nobody's been using csh).
1) Switching to the enhanced bash c++-like syntax ```[[ ]],  ==,``` etc., which is available in most modern versions of unix shells (unlike combinations of bash extension with POSIX statements) and making it consistent in the setup scripts.
2) ```function function_name () {}``` is also a mixture of several definition practices interpreted correctly in bash only. The edited way is accessible from all bash, zsh, ksh, and dash …
=> feat: Universal setup: bash, sh, zsh, ksh, dash

mcmc/MaCh3Factory.cpp
This allow to override default config with another config.
`./bin/MCMCTutorial TutorialConfigs/FitterConfig.yaml --override TutorialConfigs/Override.yaml
`
---
=> feat: Allow to override config with another config

mcmc/mcmc.cpp, mcmc/mcmc.h, python/fitter.cpp
When you start from previous you should also set numebr of steps for adaption matrices. I don't think this affected anyone but should be fixed asap
- Removed `setInitialStepNumber` people should use StartFromPrevious chain fucnitonality
---
=> breaking: Fix Setting initial steps for adaption when starting from previous chain

Parameters/ParameterHandlerBase.h, Parameters/ParameterHandlerGeneric.h, Parameters/ParameterHandlerOsc.h, Plotting/plottingUtils/inputManager.h, Plotting/plottingUtils/styleManager.h, Samples/SampleHandlerBase.h, Samples/SampleHandlerFD.cpp, Samples/SampleHandlerFD.h, python/fitters.cpp, python/parameters.cpp, python/samples.cpp, python/splines.cpp
We were using defgroup for some time but very restrictilvey. Using renaming as oprtunity to refurbish this featue.
Previously we had setters which was confusging. I decided to have ParameterHandlerSetters and sperate for SampleHandler.
This should make navigation easier. We could expand to not only have setters and getters but also interface fucntion, expand to other classes etc.
---
=> tidy: Increase usage of groups in Doxygen 

Parameters/ParameterHandlerBase.cpp, Samples/SampleHandlerFD.cpp, Samples/SampleHandlerFD.h
- Make new fucntion for inilaising arrays to avoid doing same in several places.
- When chencking kiematic bounds do not call ReturnKinematicParameter twice [I know it is setup], it is slower but I also find code hard to grasp
- Slilghtly hcange logic of fill_array. Stop calling _MP from normal FillArray. Now simply by looking at Reweight peopel should have better understanding what is going on
---
=> tidy: Avoid code duplicates in Sample Handler

Manager/Core.h, Samples/SampleHandlerFD.cpp
We have Unity which was always double, but some variabels are float or double. Pointer to float cant point to doable vice versta.
Therafore to remove lot of ugly ifdefs in the code let's intorudce 
`Unity_F `-> For floats
`Unity_D `for doubel
`Unity `for flaot or double depdning on cmake flag
Marked as breaking, as this in reality changes Old Unity into Unity_D. So expeirmental specyfic code might need to adjust sliglhy.
---
=> breaking: Reduce Unity type weirdness

cmake/Modules/CUDASetup.cmake
I haven't noticed before [maybe it is due to changes to NuOscillator] but newer cuda throws a lot of warnings.
This isn't MaCh3 only problem see:
https://mmg-gitlab.fjfi.cvut.cz/gitlab/tnl/tnl-dev/-/commit/18aeeef8988d03f3c3ae24c83f664dce17110226
https://github.com/cms-sw/cmssw/issues/33369
etc.
PS: google suggests problem started aroudn cuda 11.2, while our CI is based on 12, while I have access to 10 or 12. 
I can't check personally if 11.2 would really by ok. If someone can validate then we can redcue CUDA version requeird for addign this flag
---
=> tidy: turn off sliglhy annoing cuda warnings

Parameters/ParameterHandlerOsc.cpp, Parameters/ParameterHandlerOsc.h
Instead of hardcdoing flipping let's make simple fucniton which does this.
In near future we could expand this to get whcih param should be flipped from config [with flipping point].
This would allow to fully incorporate Osc params into HandlerGeneric().
Not doing it right now as it would be treated as breaking change [not planning any of this for 2.0.0]
Also Dr Wallace has pleny of brilliant (wacky) ideas
---
=> tidy: More flexible parameter flipping

.github/CODEOWNERS, CMakeLists.txt, Doc/Doxyfile, Samples/CMakeLists.txt, Samples/OscillationHandler.cpp, Samples/OscillationHandler.h, Samples/SampleHandlerFD.cpp, Samples/SampleHandlerFD.h
First Merge: 
https://github.com/mach3-software/MaCh3/pull/443
https://github.com/mach3-software/MaCh3/pull/443
https://github.com/mach3-software/MaCh3/pull/449
This PR creates OscillationHandler, which is simle wrapper around NuOscillator.
Similarly how we have spline handler etc.
Most of heavy lifting is still being done by NuOscillator but having seprate class allow to nicely detach parts of interface from SampelPDF.
To make it work one must merge: https://github.com/mach3-software/MaCh3Tutorial/pull/123
---
=> feat: Oscillation Handler

Parameters/ParameterHandlerGeneric.cpp, Parameters/ParameterHandlerGeneric.h, Samples/Structs.h
First merge: https://github.com/mach3-software/MaCh3/pull/443
This introudces `TypeParameterBase`, from which SplineParam, NormParams and FuncParams inherit. New function GetBaseParameter fill common variables making code less complex.
Laslty GetNormParsFromSampleName, GetFunctionalParameters uses `GetTypeParamsFromSampleName` whcih redcues code duplciate.
---
=> tidy: TypeParameterBase and unifcation of GetXParsFromSampleName

Parameters/AdaptiveMCMCHandler.cpp, Parameters/AdaptiveMCMCHandler.h, Parameters/ParameterHandlerBase.cpp
Calculating adaptive MCMC with fixed parameters was incorrect. This allows AMCMC to skip these parameters whilst adapting
- Adds ability to correctly handle fixed parameters
- Re-arranges covariance calculation to match the form in https://projecteuclid.org/journals/bernoulli/volume-7/issue-2/An-adaptive-Metropolis-algorithm/bj/1080222083.full [note the calculation is exactly the same just neater]
- Adaption now takes pointers to errors + current parameter values as part of the constructor. This removes some clunk from the interface and allows it to keep track of fixed parameters
=> feat: adaptive fix par interface

Samples/FarDetectorCoreInfoStruct.h, Samples/SampleHandlerBase.cpp, Samples/SampleHandlerBase.h, Samples/SampleHandlerFD.cpp, Samples/SampleHandlerFD.h
We should get rid of OscChannel Loop structure. This PR introduces OscChannel info, this is supposed to give idea how we should retrieve info about osc channel post OscChannel loop removal.
This retreive ability to both retrieve OscChannel index as well as pointer to it
Merge this before: https://github.com/mach3-software/MaCh3Tutorial/pull/124
---
=> breaking: Osc Channel Info

Samples/SampleHandlerFD.cpp
Recenrly two independet people forgot to add SampleNames in yaml osc. NuOscillator is throwing error that number of params is 0. So this isn;t fully neccessary.
However I figured It might be more helpfull to throw error earlier on MaCh3 level with more helfpull message
---
=> tidy: OscParams Sanity

Fitters/FitterBase.cpp, Samples/SampleHandlerBase.cpp, Samples/SampleHandlerBase.h, Samples/SampleHandlerFD.cpp, Samples/SampleHandlerFD.h, Samples/Structs.h, python/samples.cpp
Currently used loop strucutre is genrally bad for perofmance, as we can't have loop over all events but need seprate loop for each channel.
In addition this change should enable having mutiple samples in one object much easier.
First merge tutorial: https://github.com/mach3-software/MaCh3Tutorial/pull/125
I did run locally all CI and it worked (LLH scnas for example).
Sample PDF requeird minor tweaks due to not having now Osc channed index in output. However weights are identical
Here are disributons made with tutrorial.
[Test_KinemPlot.pdf](https://github.com/user-attachments/files/20229728/Test_KinemPlot.pdf)
Weights are identical, code finds issue becasue I removed osc channel from output...
---
=> breaking: Remove Oscillation Channel Loop Structure

Fitters/FitterBase.cpp
Close the covariance folder within the output file so its content is written to disk prior closing the file itself from the FitterBase destructor. That's just what the ROOT wants.
Otherwise, unfinished or interrupted chains (prior destructing the FitterBase) won't save the covariance settings.
---
=> bugfix: Write the covariance settings to disk before closing the file

Fitters/FitterBase.cpp, Fitters/LikelihoodFit.cpp, Fitters/MinuitFit.cpp, Fitters/PSO.cpp, Fitters/mcmc.cpp, Parameters/AdaptiveMCMCHandler.cpp, Parameters/AdaptiveMCMCHandler.h, Parameters/PCAHandler.cpp, Parameters/PCAHandler.h, Parameters/ParameterHandlerBase.cpp, Parameters/ParameterHandlerBase.h
I was finding ton of PCA setters and getters in CovBase bit annoing. It made diffcult to find actual methods. Now all of PCA things ahve been moved to PCA Hander. Cov Base has GetPCAHandler, so you can still get PCA info.
Anohter advatnage of having getters in PCA handler is that we no longer need if(PCA) or throw error when accessing PCA methods.
Now all atributes of PCA Handler are private memeber.
First merge: https://github.com/mach3-software/MaCh3Tutorial/pull/127
- Removed `getUseAdaptive `becasue we already had `GetDoAdaption`
---
=> tidy: Turn PCA Handler into proper class

Parameters/CMakeLists.txt, Parameters/ParameterHandlerBase.cpp, Parameters/ParameterHandlerBase.h, Parameters/ParameterHandlerGeneric.cpp, Parameters/ParameterHandlerGeneric.h, Parameters/ParameterTunes.cpp, Parameters/ParameterTunes.h, python/parameters.cpp
This allow to set turnes define in yaml simplgy doing
`Cov->SetTune("WackyTune");
`
This depracte Generated, in a sense Genrated is treated as tune, old interface to gnerated will have to be switched to newer, better.
Also removed GetNominal, it was having same purpose as GetPrior so only cofnusgin
For more see: https://github.com/mach3-software/MaCh3Tutorial/pull/126
Full pritn for debug
Normal Print
Some exmaple of error
---
=> breaking: Introdcue Tunes

Samples/FarDetectorCoreInfoStruct.h, Samples/OscillationHandler.h, Samples/SampleHandlerFD.cpp
Within old implemntation it was techcically possible to pass ATM Oscillator to Beam. Which would casue error when running NuOscillator.
Problem is it would be harder to spot.
Also tidy nEvents
---
=> feat: Make Sure shared NuOscillator has same number of paramters

Samples/SampleHandlerFD.cpp
A minor logger message update: Notify the user when you only supply YVarStr without an XVarStr in the FD sample yaml that the code will crash.
Note: This is not to be confused with checking whether there are no bins at all. 
---
=> tidy: Minor update to logger message 

Parameters/ParameterHandlerBase.cpp
Right now one could run adaption and PCA. Which would not work in a sense hard to predict outcome as parmaters in PCA base doon't use throw matrix, while there is no itnerface to use Adaption for undecomposed params. Adaption and PCA handler are independet.
Might be worth to fix it in future [if somone has time]. Right now simply throw error.
---
=> tidy: Do not allow adpation and PCA

Plotting/GetPostfitParamPlots.cpp
Make GetPostFitParamPlot app work again with files from other fitters
- remove temporary hack that was getting objects directly from file that meant app only worked on MaCh3 files 
- some other additional sanity checks to make sure configuration is valid 
- fix logic for number of violin plot files, now use number of input files instead of number of command line inputs
---
=> bugfix: Make GetPostFitParamPlots app work again

CMakeLists.txt, Manager/Core.h, Splines/SplineMonolith.cpp, cmake/Modules/CUDASetup.cmake
Becasue pedantic was being treated as compilation flag not warning flag it was leaking into GPU code too much. Which resulted in ton of warning about gcc style which were super annoing.
Remaining issues have been solved with:
https://github.com/dbarrow257/CUDAProb3/pull/8
---
=> bugfix: No more GPU compilation warnings

Parameters/ParameterHandlerBase.cpp, Parameters/ParameterHandlerBase.h
Simply Move Remaining PCA variables into PCA handler
---
=> tidy: Move remaining PCA Variables

Fitters/MCMCProcessor.cpp
Dom noticed issue when running large files.
Let's set branch to avoid weird conversion in root.
In addition imrpiove how we select Max Min. This allow to significnalty accelertae Correlation calcutions
before
after
---
=> bugfix: Improve Cachins Steps for Correlation calcautions

Parameters/ParameterHandlerBase.cpp, Parameters/ParameterHandlerBase.h, Parameters/ParameterHandlerGeneric.cpp, Parameters/ParameterHandlerGeneric.h
As we expand number of uncertanties we need better way to control parmates from various groups (xsec, flux and osc in future)
- Now we can easily bet parmater index using name
- SetGroupOnlyParameters also support setting values from vecto
- SetGroupOnlyParameters also can pass mutlple groups
---
=> feat: Expand usage of Param Group

Samples/SampleHandlerFD.cpp
This algorithm should be improved in future. But the very least we can do is to break loop once we found bin...
---
=> feat: Use break when doing bin fidning

Parameters/PCAHandler.cpp, Parameters/PCAHandler.h, Parameters/ParameterHandlerBase.cpp
By having ability to throw parmaters in PCA base we can for example evalaute how much PCA would bias our results wihtout having to run fit. This fucnitonalit is moslty used in prior/posterior predictive.
- Fix minor bug in PCA randomiz which resulted in ranomd number not being filled.
Throws in PCA base
Throws in normal base
and for other param in PCA
normal Base
So PCA throwing both conserves mean and RMS of distrubtion
---
=> feat: Parameter throwing in PCA

README.md
At this point we have quite robust cmake with multiple options. I added to readme one which could be usefull but do not need seprate paragraph.
---
=> tidy: Additional cmake options to readme

Diagnostics/GetPenaltyTerm.cpp, Fitters/MCMCProcessor.cpp, Fitters/MCMCProcessor.h, Parameters/ParameterHandlerUtils.h
Old ways of having multiple matrices requeir us to hack matcis name to be xsec_cov etc. Since Core assumed such naming cnvention it forced experiemnt specyfic to obey.
This PR introduces new getter so if there is only one TMacro [coming from GenericHandler] only this will be taken. Otherwise code will use old school hardcdoing for backward compatibility.
[Test_drawCorr.pdf](https://github.com/user-attachments/files/20625881/Test_drawCorr.pdf)
[Test.root_PenaltyTerm.pdf](https://github.com/user-attachments/files/20626433/Test.root_PenaltyTerm.pdf)
---
=> feat: Flexible Config getter from chain

Parameters/ParameterHandlerBase.cpp
If Circular Bounds would not be beyond physical bounds then MCMC would not propelry explore phase space
---
=> tidy: Ensure Circular Bounds are within Physic bounds

Samples/FarDetectorCoreInfoStruct.h, Samples/SampleHandlerFD.cpp, Samples/SampleStructs.h
Previously bin edges were per event which is waste of RAM.
In addition refactored bin finding for X which make code much neater
---
=> tidy: Bin Edeges no longer per event and add FindXBin

Samples/SampleHandlerFD.cpp
Simply make sure if bins are in increasing order othweise throw error. I think root may complain but I don't trust ROOT.
In addition there is no point in getting bins from histograms.
Workflow is that set  std::vector using bins from config. Then we make  THXD using this vector and later from TH into vector...
Last point is pointless...
---
=> feat: Check for bin ordering

Manager/Core.h, Samples/SampleHandlerBase.cpp, Samples/SampleHandlerBase.h
The changes in this pull request introduce a low MC (1e-5 = _\_LOW\_MC\_BOUND\__) cut-off to deal with low &rarr; 0 MC predictions for test statistics -LogL calculation (```GetTestStatLLH()```) as discussed in the meeting https://indico.global/event/14742/ .
The main intent is to make the test statistics to return "reasonable" LogL numbers for low MC predictions and eventually construct a "reasonable" limit for 0 MC. 0 MC predictions have clear physics motivation, but they are not allowed -- obviously --  for rigorous test statistics.  
Given data _d >= 0_ and prediction _MC >= 0_, we shall consider the test statistic is well-behaved, if:  
1. It never returns _-LogL(d,MC)_ lower than _-LogL(d,d)_, even if _MC &rarr; 0_ or MC stat error _w<sup>2</sup> &rarr; 0_.
2. It is a monotonically …
=> feat: LogL calculations for low MC predictinos and 0 MC predictions limits, GetTestStatLLH optimization

CMakeLists.txt, Samples/SampleHandlerFD.cpp, Samples/SampleHandlerFD.h
tl:dr Tidy and crackpot speed ideas
- SelectionStr wasn't used anywhere, we do store ParamToCutOnIt  so we can always revert it using map
-  SplineVarNames  only used during setup so no point having it class member
- removed not used Set2DBinning and Set1DBinning
- some hyper optimisation like caching size of vector whcih helps compiler optimsie entires [and using int not size which is smaller] or storing reference to Selection which helps caching
In my few trials there is a few percent increase. Nothing major but "Tesco: every little helps"
---
=> tidy: Removal of oboslete stuff and micro optimisation

Manager/YamlHelper.h
Basically Dan pointer out that error "empty yaml" isn;t very helpufll so this should imrpove htis
Sadly yaml don't store information back so I don't think we can fully trace path back wihtout changing how Get<> works
Before:
After:
---
=> tidy: More helpfull yaml error messages

Parameters/ParameterHandlerBase.cpp
To solve confusion widlards are supported on parmater side i.e. parmater can be applied to wildarc sample.
Sample should not have this widlcard feature otheriwse things would get convluted.
This came during dsicusision with Dan. Now error should be clear with error.
---
=> tidy: Wildcard sanitizer

Fitters/mcmc.cpp, Samples/SampleHandlerFD.cpp
Simple use STL over TMath. Funnily enoug TMath was calling some STL fucntions already so this is to reduce relliance on ROOT rather than any perfomace.
Also now stepStart + chainLength is calcuated once and set const. Previously it tehccinally could be calculated every iteration unless compiler was smart enough to figure out this on it's own. Even if it is faster impact would be negligilbe so I didn't test it.
---
=> feat: Use STL over TMath

Fitters/FitterBase.cpp, Fitters/StatisticalUtils.cpp, Samples/HistogramUtils.cpp, Samples/HistogramUtils.h
Dan suggested that if one puts wrong file name for example foldr which do not exist MaCh3 will not stop and run whole chain. Which will leave user wondering where chain is...
This wrapper is mean to fix this. I will udpate other parts of the code to use this wrapper in future.
---
=> feat: Wrapper around Open to safegarud from missconfigured paths

Parameters/ParameterHandlerBase.cpp, Parameters/ParameterHandlerBase.h
Dan raised issue that even if we fixed param code might still apply special proposal like flipping.
Just to be completly safe turn off speical proposal for fixed params
---
=> feat: Do not apply special proposal for fixed params

.github/workflows/CIValidations.yml, Parameters/AdaptiveMCMCHandler.cpp, Parameters/AdaptiveMCMCHandler.h
Becasue `adaptive_save_n_iterations  `by deafult was 1 it was saving adaptive matrix every time udpate adaptive was called.
In addition use MaCh3CLI for bots
---
=> tidy: Stop Saving Adatpive So often

Parameters/ParameterHandlerBase.cpp
If somone tries to intialsie adaption after it was done let's give warning.
We could consider throwing error.
---
=> tidy: do not allow adaption to be initialsied twice

Fitters/MCMCProcessor.cpp
Most changes inspired by talking with Dan
- Previously we were plotting param overlay (identical) twice
- Stop weird flux legacy hard-coding
- Now we plot several plots based on value of interval
- Y axis range is auto adjustable, no hard-coding :)
---
=> tidy: Improve Plotting param overlay

Fitters/mcmc.cpp, Fitters/mcmc.h
MaCh3 was storing proposed sample/systematic likelihoods in syst/sample_llh. This means that, when saving steps to chain, each step's individual likelihoods were those of the last proposed step. This results in weirdness like systematic LLHs showing loads of out of bounds steps.
- Add separate sample/systematic likelihood vectors for proposed step
- Swap to usual vector when step saved
Now Xsec likelihoods look more reasonable:
---
=> bugfix: Store correct syst/sample likelihoods when saving steps in MCMC

Fitters/FitterBase.cpp, Fitters/MCMCProcessor.cpp, Fitters/MCMCProcessor.h, Fitters/OscProcessor.cpp, Fitters/PredictiveThrower.cpp, Fitters/mcmc.cpp
Within Fitter base step number was Unsinged Int however it was saved as int and whole processing was using int.
This is attempt to unify this
---
=> tidy: unify wheter step is UInt or Int
